package main

import (
	"bufio"
	"context"
	"crypto/rand"
	"encoding/json"
	"fmt"
	"math"
	"math/big"
	"os"
	"os/signal"
	"path/filepath"
	"sync"
	"sync/atomic"
	"time"

	"github.com/celestiaorg/celestia-app/v6/app"
	"github.com/celestiaorg/celestia-app/v6/app/encoding"
	"github.com/celestiaorg/celestia-app/v6/fibre"
	fibregrpc "github.com/celestiaorg/celestia-app/v6/fibre/grpc"
	"github.com/celestiaorg/celestia-app/v6/fibre/validator"
	"github.com/celestiaorg/go-square/v3/share"

	coregrpc "github.com/cometbft/cometbft/rpc/grpc"
	core "github.com/cometbft/cometbft/types"
	"github.com/cosmos/cosmos-sdk/crypto/hd"
	"github.com/cosmos/cosmos-sdk/crypto/keyring"
	sdk "github.com/cosmos/cosmos-sdk/types"
	banktypes "github.com/cosmos/cosmos-sdk/x/bank/types"
	"github.com/spf13/cobra"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
)

const (
	defaultEndpoint    = "localhost:9091"
	defaultKeyringDir  = ".celestia-app"
	defaultKeyName     = "fibre-blast-key"
	defaultPayloadSize = 128 * 1024 * 1024 // 128MiB
	defaultNamespace   = "fibre"
	defaultChainID     = "celestia"
	defaultTracesDir   = ".celestia-app/data/traces"
	defaultWorkers     = 4
)

var (
	endpoint          string
	keyringDir        string
	payloadSize       int
	namespaceStr      string
	validatorHostFile string
	chainID           string
	tracesDir         string
	maxInflight       int
	uploadConcurrency int
)

var rootCmd = &cobra.Command{
	Use:   "validator-blast",
	Short: "Continuously uploads large blobs to the Fibre validator mesh",
	RunE: func(cmd *cobra.Command, args []string) error {
		// default keyring dir
		if keyringDir == "" {
			home, err := os.UserHomeDir()
			if err != nil {
				return fmt.Errorf("getting home directory: %w", err)
			}
			keyringDir = filepath.Join(home, defaultKeyringDir)
		}

		// default traces dir
		if tracesDir == "" {
			home, err := os.UserHomeDir()
			if err != nil {
				return fmt.Errorf("getting home directory: %w", err)
			}
			tracesDir = filepath.Join(home, defaultTracesDir)
		}

		if maxInflight <= 0 {
			return fmt.Errorf("max-inflight must be positive")
		}
		if uploadConcurrency <= 0 {
			return fmt.Errorf("upload-concurrency must be positive")
		}
		if payloadSize <= 0 {
			return fmt.Errorf("payload size must be positive")
		}

		ctx, cancel := context.WithCancel(cmd.Context())
		defer cancel()

		// handle Ctrl+C
		sigChan := make(chan os.Signal, 1)
		signal.Notify(sigChan, os.Interrupt)
		go func() {
			for range sigChan {
				fmt.Println("\nInterrupt received, shutting down...")
				cancel()
			}
		}()

		return runBlast(ctx)
	},
}

func init() {
	rootCmd.Flags().StringVarP(&endpoint, "grpc-endpoint", "e", defaultEndpoint, "gRPC endpoint for consensus queries (validator set/head)")
	rootCmd.Flags().StringVarP(&keyringDir, "keyring-dir", "k", "", "directory containing the keyring (defaults to ~/.celestia-app)")
	rootCmd.Flags().IntVarP(&payloadSize, "payload-size", "s", defaultPayloadSize, "size of payload data in bytes")
	rootCmd.Flags().StringVarP(&namespaceStr, "namespace", "n", defaultNamespace, "namespace for blob uploads")
	rootCmd.Flags().StringVarP(&validatorHostFile, "validator-hosts", "v", "", "path to validator host mapping generated by talis (required)")
	rootCmd.Flags().StringVarP(&chainID, "chain-id", "c", defaultChainID, "chain ID to embed in payment promises (env CHAIN_ID takes precedence)")
	rootCmd.Flags().StringVarP(&tracesDir, "traces-dir", "t", "", "directory to write trace metrics (defaults to ~/.celestia-app/data/traces)")
	rootCmd.Flags().IntVarP(&maxInflight, "max-inflight", "m", defaultWorkers, "number of concurrent blob uploads to run per node")
	rootCmd.Flags().IntVar(&uploadConcurrency, "upload-concurrency", 100, "number of parallel validator RPCs per blob inside the Fibre client")

	rootCmd.MarkFlagRequired("validator-hosts")
}

func main() {
	// allow env override for chain id
	if envChain := os.Getenv("CHAIN_ID"); envChain != "" {
		chainID = envChain
	}

	if err := rootCmd.Execute(); err != nil {
		os.Exit(1)
	}
}

func runBlast(ctx context.Context) error {
	fmt.Println("Validator Blast")
	fmt.Println("================")
	fmt.Printf("Consensus gRPC endpoint: %s\n", endpoint)
	fmt.Printf("Validator hosts file: %s\n", validatorHostFile)
	fmt.Printf("Keyring directory: %s\n", keyringDir)
	fmt.Printf("Chain ID: %s\n", chainID)
	fmt.Printf("Namespace: %s\n", namespaceStr)
	fmt.Printf("Payload size: %d bytes\n", payloadSize)
	fmt.Printf("Max inflight uploads: %d\n", maxInflight)
	fmt.Printf("Upload concurrency: %d validators at once\n\n", uploadConcurrency)

	// connect to consensus node
	grpcConn, err := grpc.NewClient(
		endpoint,
		grpc.WithTransportCredentials(insecure.NewCredentials()),
		grpc.WithDefaultCallOptions(
			grpc.MaxCallSendMsgSize(math.MaxInt32),
			grpc.MaxCallRecvMsgSize(math.MaxInt32),
		),
	)
	if err != nil {
		return fmt.Errorf("creating consensus gRPC client: %w", err)
	}
	defer grpcConn.Close()

	encCfg := encoding.MakeConfig(app.ModuleEncodingRegisters...)

	kr, keyName, address, err := setupKeyring(ctx, keyringDir, encCfg, grpcConn)
	if err != nil {
		return fmt.Errorf("setting up keyring: %w", err)
	}
	fmt.Printf("Using key %s (%s)\n", keyName, address)

	validatorHosts, err := loadValidatorHosts(validatorHostFile)
	if err != nil {
		return fmt.Errorf("loading validator hosts: %w", err)
	}

	hostRegistry := newStaticHostRegistry(validatorHosts)
	valGetter := &cachedSetGetter{
		underlying: fibregrpc.NewSetGetter(coregrpc.NewBlockAPIClient(grpcConn)),
	}

	cfg := fibre.DefaultClientConfig()
	cfg.DefaultKeyName = keyName
	cfg.ChainID = chainID
	cfg.UploadConcurrency = uploadConcurrency
	cfg.AutoFundEscrow = false

	fibreClient, err := fibre.NewClient(nil, kr, valGetter, hostRegistry, cfg)
	if err != nil {
		return fmt.Errorf("creating fibre client: %w", err)
	}
	defer fibreClient.Close()

	namespace, err := fibreNamespace(namespaceStr)
	if err != nil {
		return err
	}

	fmt.Printf("Generating reusable %d-byte blob...\n", payloadSize)
	blobData := make([]byte, payloadSize)
	if _, err := rand.Read(blobData); err != nil {
		return fmt.Errorf("generating random blob data: %w", err)
	}
	blob, err := fibre.NewBlob(blobData, cfg.BlobConfig)
	if err != nil {
		return fmt.Errorf("encoding blob: %w", err)
	}

	metrics, err := newMetricsWriter(tracesDir, "validator-blast")
	if err != nil {
		return fmt.Errorf("creating metrics writer: %w", err)
	}
	defer metrics.Close()

	fmt.Println("Starting blast loop. Press Ctrl+C to stop.")
	fmt.Println()

	var (
		wg      sync.WaitGroup
		txCount atomic.Uint64
	)

	workerCtx, cancelWorkers := context.WithCancel(ctx)
	defer cancelWorkers()

	for i := 0; i < maxInflight; i++ {
		wg.Add(1)
		go func(workerID int) {
			defer wg.Done()
			for {
				if err := workerCtx.Err(); err != nil {
					return
				}
				txNum := txCount.Add(1)
				start := time.Now()
				result, err := fibreClient.Upload(workerCtx, namespace, blob)
				end := time.Now()
				if err != nil {
					fmt.Printf("[worker %d] upload %d failed: %v\n", workerID, txNum, err)
					_ = metrics.WriteMetric(TxMetric{
						TxNum:       txNum,
						StartTime:   start,
						EndTime:     end,
						Success:     false,
						Error:       err.Error(),
						PayloadSize: payloadSize,
					})
					continue
				}

				latency := end.Sub(start)
				fmt.Printf("[worker %d] uploaded blob %s in %s (height ~%d)\n",
					workerID, blob.Commitment().String(), latency, result.PaymentPromise.Height)

				_ = metrics.WriteMetric(TxMetric{
					TxNum:       txNum,
					StartTime:   start,
					EndTime:     end,
					Success:     true,
					Height:      result.PaymentPromise.Height,
					PayloadSize: payloadSize,
					LatencyMs:   latency.Milliseconds(),
				})
				_ = metrics.WriteBlobMetric(BlobMetric{
					Size:        payloadSize,
					SubmittedAt: end,
					Height:      result.PaymentPromise.Height,
				})
			}
		}(i)
	}

	<-ctx.Done()
	cancelWorkers()
	fmt.Println("Shutting down workers...")
	wg.Wait()
	fmt.Printf("Total uploads attempted: %d\n", txCount.Load())
	return nil
}

func fibreNamespace(ns string) (share.Namespace, error) {
	namespace, err := share.NewV0Namespace([]byte(ns))
	if err != nil {
		return share.Namespace{}, fmt.Errorf("invalid namespace %q: %w", ns, err)
	}
	return namespace, nil
}

// setupKeyring mirrors the fibre-load helper: it ensures a usable key exists.
func setupKeyring(ctx context.Context, keyringDir string, encCfg encoding.Config, grpcConn *grpc.ClientConn) (keyring.Keyring, string, string, error) {
	if err := os.MkdirAll(keyringDir, 0o700); err != nil {
		return nil, "", "", fmt.Errorf("creating keyring dir: %w", err)
	}

	kr, err := keyring.New(app.Name, keyring.BackendTest, keyringDir, nil, encCfg.Codec)
	if err != nil {
		return nil, "", "", fmt.Errorf("initializing keyring: %w", err)
	}

	keys, err := kr.List()
	if err != nil {
		return nil, "", "", fmt.Errorf("listing keys: %w", err)
	}

	var record *keyring.Record
	var name string

	if len(keys) == 0 {
		fmt.Println("No keys found, creating a new one for validator-blast...")
		keyInfo, _, err := kr.NewMnemonic(
			defaultKeyName,
			keyring.English,
			sdk.GetConfig().GetFullBIP44Path(),
			"",
			hd.Secp256k1,
		)
		if err != nil {
			return nil, "", "", fmt.Errorf("creating new key: %w", err)
		}
		record = keyInfo
		name = defaultKeyName
	} else {
		fmt.Printf("Found %d key(s); selecting the richest...\n", len(keys))

		bankClient := banktypes.NewQueryClient(grpcConn)
		maxBalance := big.NewInt(0)
		for _, key := range keys {
			addr, err := key.GetAddress()
			if err != nil {
				fmt.Printf("  skipping key %s: %v\n", key.Name, err)
				continue
			}

			resp, err := bankClient.AllBalances(ctx, &banktypes.QueryAllBalancesRequest{
				Address: addr.String(),
			})
			if err != nil {
				fmt.Printf("  failed to query balance for %s: %v\n", key.Name, err)
				continue
			}

			total := big.NewInt(0)
			for _, coin := range resp.Balances {
				if coin.Amount.IsPositive() {
					total.Add(total, coin.Amount.BigInt())
				}
			}

			fmt.Printf("  %s (%s): %s utia\n", key.Name, addr.String(), total.String())
			if total.Cmp(maxBalance) > 0 {
				maxBalance = total
				record = key
				name = key.Name
			}
		}

		if record == nil {
			record = keys[0]
			name = record.Name
		}
	}

	addr, err := record.GetAddress()
	if err != nil {
		return nil, "", "", fmt.Errorf("getting key address: %w", err)
	}

	return kr, name, addr.String(), nil
}

func loadValidatorHosts(filePath string) (map[string]string, error) {
	data, err := os.ReadFile(filePath)
	if err != nil {
		return nil, fmt.Errorf("reading validator hosts file: %w", err)
	}

	var hosts map[string]string
	if err := json.Unmarshal(data, &hosts); err != nil {
		return nil, fmt.Errorf("parsing validator hosts: %w", err)
	}
	if len(hosts) == 0 {
		return nil, fmt.Errorf("validator hosts file is empty")
	}
	return hosts, nil
}

type staticHostRegistry struct {
	hosts map[string]string
}

func newStaticHostRegistry(hosts map[string]string) *staticHostRegistry {
	return &staticHostRegistry{hosts: hosts}
}

func (r *staticHostRegistry) GetHost(ctx context.Context, val *core.Validator) (validator.Host, error) {
	addr := val.Address.String()
	host, ok := r.hosts[addr]
	if !ok {
		return "", fmt.Errorf("no host configured for validator %s", addr)
	}
	return validator.Host(host), nil
}

type cachedSetGetter struct {
	underlying validator.SetGetter
	once       sync.Once
	cached     validator.Set
	err        error
}

func (c *cachedSetGetter) Head(ctx context.Context) (validator.Set, error) {
	c.once.Do(func() {
		c.cached, c.err = c.underlying.Head(ctx)
	})
	return c.cached, c.err
}

func (c *cachedSetGetter) GetByHeight(ctx context.Context, height uint64) (validator.Set, error) {
	return c.underlying.GetByHeight(ctx, height)
}

type TxMetric struct {
	TxNum       uint64    `json:"tx_num"`
	StartTime   time.Time `json:"start_time"`
	EndTime     time.Time `json:"end_time"`
	Success     bool      `json:"success"`
	TxHash      string    `json:"tx_hash,omitempty"`
	Height      uint64    `json:"height,omitempty"`
	Error       string    `json:"error,omitempty"`
	PayloadSize int       `json:"payload_size"`
	LatencyMs   int64     `json:"latency_ms,omitempty"`
}

type BlobMetric struct {
	Size        int       `json:"size"`
	SubmittedAt time.Time `json:"submitted_at"`
	TxHash      string    `json:"tx_hash,omitempty"`
	Height      uint64    `json:"height,omitempty"`
}

type metricsWriter struct {
	name       string
	file       *os.File
	writer     *bufio.Writer
	blobFile   *os.File
	blobWriter *bufio.Writer
	mu         sync.Mutex
	blobMu     sync.Mutex
}

func newMetricsWriter(tracesDir, toolName string) (*metricsWriter, error) {
	if err := os.MkdirAll(tracesDir, 0o755); err != nil {
		return nil, fmt.Errorf("creating traces dir: %w", err)
	}

	metricsPath := filepath.Join(tracesDir, fmt.Sprintf("%s-metrics.jsonl", toolName))
	file, err := os.Create(metricsPath)
	if err != nil {
		return nil, fmt.Errorf("creating metrics file: %w", err)
	}
	fmt.Printf("Writing metrics to %s\n", metricsPath)

	blobPath := filepath.Join(tracesDir, "blobs.jsonl")
	blobFile, err := os.OpenFile(blobPath, os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0o644)
	if err != nil {
		file.Close()
		return nil, fmt.Errorf("opening blob metrics: %w", err)
	}
	fmt.Printf("Appending blob records to %s\n", blobPath)

	return &metricsWriter{
		name:       toolName,
		file:       file,
		writer:     bufio.NewWriter(file),
		blobFile:   blobFile,
		blobWriter: bufio.NewWriter(blobFile),
	}, nil
}

func (m *metricsWriter) WriteMetric(metric TxMetric) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	data, err := json.Marshal(metric)
	if err != nil {
		return err
	}
	if _, err := m.writer.Write(data); err != nil {
		return err
	}
	if err := m.writer.WriteByte('\n'); err != nil {
		return err
	}
	return m.writer.Flush()
}

func (m *metricsWriter) WriteBlobMetric(metric BlobMetric) error {
	m.blobMu.Lock()
	defer m.blobMu.Unlock()

	data, err := json.Marshal(metric)
	if err != nil {
		return err
	}
	if _, err := m.blobWriter.Write(data); err != nil {
		return err
	}
	if err := m.blobWriter.WriteByte('\n'); err != nil {
		return err
	}
	return m.blobWriter.Flush()
}

func (m *metricsWriter) Close() error {
	m.mu.Lock()
	defer m.mu.Unlock()
	if err := m.writer.Flush(); err != nil {
		return err
	}
	if err := m.file.Close(); err != nil {
		return err
	}
	m.blobMu.Lock()
	defer m.blobMu.Unlock()
	if err := m.blobWriter.Flush(); err != nil {
		return err
	}
	return m.blobFile.Close()
}
