// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: celestia/fibre/v1/event.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// EventDepositToEscrow is emitted when a deposit is made to an escrow account.
type EventDepositToEscrow struct {
	Signer string     `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	Amount types.Coin `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount"`
}

func (m *EventDepositToEscrow) Reset()         { *m = EventDepositToEscrow{} }
func (m *EventDepositToEscrow) String() string { return proto.CompactTextString(m) }
func (*EventDepositToEscrow) ProtoMessage()    {}
func (*EventDepositToEscrow) Descriptor() ([]byte, []int) {
	return fileDescriptor_02fd497617eb1003, []int{0}
}
func (m *EventDepositToEscrow) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventDepositToEscrow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventDepositToEscrow.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventDepositToEscrow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventDepositToEscrow.Merge(m, src)
}
func (m *EventDepositToEscrow) XXX_Size() int {
	return m.Size()
}
func (m *EventDepositToEscrow) XXX_DiscardUnknown() {
	xxx_messageInfo_EventDepositToEscrow.DiscardUnknown(m)
}

var xxx_messageInfo_EventDepositToEscrow proto.InternalMessageInfo

func (m *EventDepositToEscrow) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *EventDepositToEscrow) GetAmount() types.Coin {
	if m != nil {
		return m.Amount
	}
	return types.Coin{}
}

// EventWithdrawFromEscrowRequest is emitted when a withdrawal is requested from an escrow account.
type EventWithdrawFromEscrowRequest struct {
	Signer      string     `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	Amount      types.Coin `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount"`
	RequestedAt time.Time  `protobuf:"bytes,3,opt,name=requested_at,json=requestedAt,proto3,stdtime" json:"requested_at"`
	AvailableAt time.Time  `protobuf:"bytes,4,opt,name=available_at,json=availableAt,proto3,stdtime" json:"available_at"`
}

func (m *EventWithdrawFromEscrowRequest) Reset()         { *m = EventWithdrawFromEscrowRequest{} }
func (m *EventWithdrawFromEscrowRequest) String() string { return proto.CompactTextString(m) }
func (*EventWithdrawFromEscrowRequest) ProtoMessage()    {}
func (*EventWithdrawFromEscrowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_02fd497617eb1003, []int{1}
}
func (m *EventWithdrawFromEscrowRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventWithdrawFromEscrowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventWithdrawFromEscrowRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventWithdrawFromEscrowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventWithdrawFromEscrowRequest.Merge(m, src)
}
func (m *EventWithdrawFromEscrowRequest) XXX_Size() int {
	return m.Size()
}
func (m *EventWithdrawFromEscrowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EventWithdrawFromEscrowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EventWithdrawFromEscrowRequest proto.InternalMessageInfo

func (m *EventWithdrawFromEscrowRequest) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *EventWithdrawFromEscrowRequest) GetAmount() types.Coin {
	if m != nil {
		return m.Amount
	}
	return types.Coin{}
}

func (m *EventWithdrawFromEscrowRequest) GetRequestedAt() time.Time {
	if m != nil {
		return m.RequestedAt
	}
	return time.Time{}
}

func (m *EventWithdrawFromEscrowRequest) GetAvailableAt() time.Time {
	if m != nil {
		return m.AvailableAt
	}
	return time.Time{}
}

// EventWithdrawFromEscrowExecuted is emitted when a withdrawal is processed.
type EventWithdrawFromEscrowExecuted struct {
	Signer string     `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	Amount types.Coin `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount"`
}

func (m *EventWithdrawFromEscrowExecuted) Reset()         { *m = EventWithdrawFromEscrowExecuted{} }
func (m *EventWithdrawFromEscrowExecuted) String() string { return proto.CompactTextString(m) }
func (*EventWithdrawFromEscrowExecuted) ProtoMessage()    {}
func (*EventWithdrawFromEscrowExecuted) Descriptor() ([]byte, []int) {
	return fileDescriptor_02fd497617eb1003, []int{2}
}
func (m *EventWithdrawFromEscrowExecuted) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventWithdrawFromEscrowExecuted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventWithdrawFromEscrowExecuted.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventWithdrawFromEscrowExecuted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventWithdrawFromEscrowExecuted.Merge(m, src)
}
func (m *EventWithdrawFromEscrowExecuted) XXX_Size() int {
	return m.Size()
}
func (m *EventWithdrawFromEscrowExecuted) XXX_DiscardUnknown() {
	xxx_messageInfo_EventWithdrawFromEscrowExecuted.DiscardUnknown(m)
}

var xxx_messageInfo_EventWithdrawFromEscrowExecuted proto.InternalMessageInfo

func (m *EventWithdrawFromEscrowExecuted) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *EventWithdrawFromEscrowExecuted) GetAmount() types.Coin {
	if m != nil {
		return m.Amount
	}
	return types.Coin{}
}

// EventPayForFibre is emitted when a payment for fibre is processed.
type EventPayForFibre struct {
	Signer     string `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	Namespace  []byte `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Commitment []byte `protobuf:"bytes,3,opt,name=commitment,proto3" json:"commitment,omitempty"`
}

func (m *EventPayForFibre) Reset()         { *m = EventPayForFibre{} }
func (m *EventPayForFibre) String() string { return proto.CompactTextString(m) }
func (*EventPayForFibre) ProtoMessage()    {}
func (*EventPayForFibre) Descriptor() ([]byte, []int) {
	return fileDescriptor_02fd497617eb1003, []int{3}
}
func (m *EventPayForFibre) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventPayForFibre) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventPayForFibre.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventPayForFibre) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventPayForFibre.Merge(m, src)
}
func (m *EventPayForFibre) XXX_Size() int {
	return m.Size()
}
func (m *EventPayForFibre) XXX_DiscardUnknown() {
	xxx_messageInfo_EventPayForFibre.DiscardUnknown(m)
}

var xxx_messageInfo_EventPayForFibre proto.InternalMessageInfo

func (m *EventPayForFibre) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *EventPayForFibre) GetNamespace() []byte {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *EventPayForFibre) GetCommitment() []byte {
	if m != nil {
		return m.Commitment
	}
	return nil
}

// EventPaymentPromiseTimeout is emitted when a PaymentPromise timeout is processed.
type EventPaymentPromiseTimeout struct {
	Processor          string `protobuf:"bytes,1,opt,name=processor,proto3" json:"processor,omitempty"`
	EscrowSigner       string `protobuf:"bytes,2,opt,name=escrow_signer,json=escrowSigner,proto3" json:"escrow_signer,omitempty"`
	PaymentPromiseHash []byte `protobuf:"bytes,3,opt,name=payment_promise_hash,json=paymentPromiseHash,proto3" json:"payment_promise_hash,omitempty"`
}

func (m *EventPaymentPromiseTimeout) Reset()         { *m = EventPaymentPromiseTimeout{} }
func (m *EventPaymentPromiseTimeout) String() string { return proto.CompactTextString(m) }
func (*EventPaymentPromiseTimeout) ProtoMessage()    {}
func (*EventPaymentPromiseTimeout) Descriptor() ([]byte, []int) {
	return fileDescriptor_02fd497617eb1003, []int{4}
}
func (m *EventPaymentPromiseTimeout) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventPaymentPromiseTimeout) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventPaymentPromiseTimeout.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventPaymentPromiseTimeout) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventPaymentPromiseTimeout.Merge(m, src)
}
func (m *EventPaymentPromiseTimeout) XXX_Size() int {
	return m.Size()
}
func (m *EventPaymentPromiseTimeout) XXX_DiscardUnknown() {
	xxx_messageInfo_EventPaymentPromiseTimeout.DiscardUnknown(m)
}

var xxx_messageInfo_EventPaymentPromiseTimeout proto.InternalMessageInfo

func (m *EventPaymentPromiseTimeout) GetProcessor() string {
	if m != nil {
		return m.Processor
	}
	return ""
}

func (m *EventPaymentPromiseTimeout) GetEscrowSigner() string {
	if m != nil {
		return m.EscrowSigner
	}
	return ""
}

func (m *EventPaymentPromiseTimeout) GetPaymentPromiseHash() []byte {
	if m != nil {
		return m.PaymentPromiseHash
	}
	return nil
}

// EventUpdateFibreParams is emitted when fibre parameters are updated.
type EventUpdateFibreParams struct {
	Signer string `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	Params Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *EventUpdateFibreParams) Reset()         { *m = EventUpdateFibreParams{} }
func (m *EventUpdateFibreParams) String() string { return proto.CompactTextString(m) }
func (*EventUpdateFibreParams) ProtoMessage()    {}
func (*EventUpdateFibreParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_02fd497617eb1003, []int{5}
}
func (m *EventUpdateFibreParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventUpdateFibreParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventUpdateFibreParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventUpdateFibreParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventUpdateFibreParams.Merge(m, src)
}
func (m *EventUpdateFibreParams) XXX_Size() int {
	return m.Size()
}
func (m *EventUpdateFibreParams) XXX_DiscardUnknown() {
	xxx_messageInfo_EventUpdateFibreParams.DiscardUnknown(m)
}

var xxx_messageInfo_EventUpdateFibreParams proto.InternalMessageInfo

func (m *EventUpdateFibreParams) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *EventUpdateFibreParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func init() {
	proto.RegisterType((*EventDepositToEscrow)(nil), "celestia.fibre.v1.EventDepositToEscrow")
	proto.RegisterType((*EventWithdrawFromEscrowRequest)(nil), "celestia.fibre.v1.EventWithdrawFromEscrowRequest")
	proto.RegisterType((*EventWithdrawFromEscrowExecuted)(nil), "celestia.fibre.v1.EventWithdrawFromEscrowExecuted")
	proto.RegisterType((*EventPayForFibre)(nil), "celestia.fibre.v1.EventPayForFibre")
	proto.RegisterType((*EventPaymentPromiseTimeout)(nil), "celestia.fibre.v1.EventPaymentPromiseTimeout")
	proto.RegisterType((*EventUpdateFibreParams)(nil), "celestia.fibre.v1.EventUpdateFibreParams")
}

func init() { proto.RegisterFile("celestia/fibre/v1/event.proto", fileDescriptor_02fd497617eb1003) }

var fileDescriptor_02fd497617eb1003 = []byte{
	// 568 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x94, 0x3f, 0x6f, 0x13, 0x31,
	0x18, 0xc6, 0xe3, 0x50, 0x45, 0xc4, 0x0d, 0x12, 0x9c, 0x22, 0x94, 0x46, 0x70, 0xa9, 0x32, 0x75,
	0xe9, 0x5d, 0x03, 0x12, 0x4c, 0x0c, 0x09, 0x24, 0x20, 0xb1, 0x44, 0xd7, 0x22, 0x24, 0x96, 0xc8,
	0x77, 0xf7, 0xf6, 0x62, 0x29, 0x3e, 0x1b, 0xdb, 0x97, 0xb6, 0x23, 0xb0, 0x32, 0xf4, 0x0b, 0xf0,
	0x2d, 0xf8, 0x0a, 0x48, 0x1d, 0x2b, 0x26, 0x26, 0x40, 0xc9, 0x17, 0x41, 0x67, 0xdf, 0x25, 0xfc,
	0x11, 0xaa, 0xda, 0xa1, 0x9b, 0xed, 0xf7, 0x79, 0x5f, 0xff, 0xfc, 0x3e, 0xb6, 0xf1, 0xfd, 0x08,
	0x66, 0xa0, 0x34, 0x25, 0xfe, 0x21, 0x0d, 0x25, 0xf8, 0xf3, 0x9e, 0x0f, 0x73, 0x48, 0xb5, 0x27,
	0x24, 0xd7, 0xdc, 0xb9, 0x53, 0x86, 0x3d, 0x13, 0xf6, 0xe6, 0xbd, 0x76, 0x33, 0xe1, 0x09, 0x37,
	0x51, 0x3f, 0x1f, 0x59, 0x61, 0xbb, 0x93, 0x70, 0x9e, 0xcc, 0xc0, 0x37, 0xb3, 0x30, 0x3b, 0xf4,
	0x35, 0x65, 0xa0, 0x34, 0x61, 0xa2, 0x10, 0xb8, 0x11, 0x57, 0x8c, 0x2b, 0x3f, 0x24, 0x2a, 0xdf,
	0x25, 0x04, 0x4d, 0x7a, 0x7e, 0xc4, 0x69, 0x5a, 0xc4, 0xb7, 0x6c, 0x7c, 0x62, 0x2b, 0xdb, 0xc9,
	0x2a, 0xf5, 0x1f, 0x46, 0x41, 0x24, 0x61, 0x45, 0xbc, 0xfb, 0x0e, 0xe1, 0xe6, 0x30, 0x87, 0x7e,
	0x06, 0x82, 0x2b, 0xaa, 0x0f, 0xf8, 0x50, 0x45, 0x92, 0x1f, 0x39, 0x7b, 0xb8, 0xa6, 0x68, 0x92,
	0x82, 0x6c, 0xa1, 0x6d, 0xb4, 0x53, 0x1f, 0xb4, 0xbe, 0x7e, 0xde, 0x6d, 0x16, 0xa5, 0xfb, 0x71,
	0x2c, 0x41, 0xa9, 0x7d, 0x2d, 0x69, 0x9a, 0x04, 0x85, 0xce, 0x79, 0x8c, 0x6b, 0x84, 0xf1, 0x2c,
	0xd5, 0xad, 0xea, 0x36, 0xda, 0xd9, 0x7c, 0xb0, 0xe5, 0x15, 0xf2, 0x1c, 0xdb, 0x2b, 0xb0, 0xbd,
	0xa7, 0x9c, 0xa6, 0x83, 0x8d, 0xb3, 0xef, 0x9d, 0x4a, 0x50, 0xc8, 0xbb, 0x9f, 0xaa, 0xd8, 0x35,
	0x0c, 0xaf, 0xa9, 0x9e, 0xc6, 0x92, 0x1c, 0x8d, 0x24, 0x67, 0x16, 0x23, 0x80, 0xb7, 0x19, 0x28,
	0x7d, 0x8d, 0x34, 0xce, 0x73, 0xdc, 0x90, 0x76, 0x57, 0x88, 0x27, 0x44, 0xb7, 0x6e, 0x98, 0xf4,
	0xb6, 0x67, 0x4d, 0xf2, 0x4a, 0x93, 0xbc, 0x83, 0xd2, 0xa4, 0xc1, 0xcd, 0x3c, 0xff, 0xf4, 0x47,
	0x07, 0x05, 0x9b, 0xab, 0xcc, 0xbe, 0x29, 0x44, 0xe6, 0x84, 0xce, 0x48, 0x38, 0x83, 0xbc, 0xd0,
	0xc6, 0x65, 0x0a, 0xad, 0x32, 0xfb, 0xba, 0xfb, 0x11, 0xe1, 0xce, 0x7f, 0xfa, 0x33, 0x3c, 0x86,
	0x28, 0xd3, 0x10, 0x5f, 0xa7, 0x5d, 0xef, 0x11, 0xbe, 0x6d, 0x70, 0xc6, 0xe4, 0x64, 0xc4, 0xe5,
	0x28, 0xbf, 0x57, 0x57, 0xd8, 0xff, 0x1e, 0xae, 0xa7, 0x84, 0x81, 0x12, 0x24, 0x02, 0x83, 0xd0,
	0x08, 0xd6, 0x0b, 0x8e, 0x8b, 0x71, 0xc4, 0x19, 0xa3, 0x9a, 0x41, 0x6a, 0x3d, 0x68, 0x04, 0xbf,
	0xad, 0x74, 0xbf, 0x20, 0xdc, 0x2e, 0x21, 0xf2, 0x85, 0xb1, 0xe4, 0x8c, 0x2a, 0xc8, 0x7b, 0xc9,
	0x33, 0xed, 0x3c, 0xc2, 0x75, 0x21, 0x79, 0x04, 0x4a, 0xf1, 0x8b, 0x89, 0xd6, 0x52, 0xe7, 0x09,
	0xbe, 0x05, 0xa6, 0xb1, 0x93, 0xe2, 0x34, 0xd5, 0x0b, 0x72, 0x1b, 0x56, 0xbe, 0x6f, 0xcf, 0xb4,
	0x87, 0x9b, 0xc2, 0xf2, 0xe4, 0x6f, 0x31, 0x07, 0x9a, 0x4c, 0x89, 0x9a, 0x16, 0xfc, 0x8e, 0xf8,
	0x83, 0xf5, 0x05, 0x51, 0xd3, 0xee, 0x07, 0x84, 0xef, 0x9a, 0x73, 0xbc, 0x12, 0x31, 0xd1, 0x60,
	0x9a, 0x39, 0x36, 0x0f, 0xf4, 0x6a, 0x96, 0xda, 0xc7, 0xbd, 0xb6, 0xf4, 0xef, 0x2f, 0xc8, 0xb3,
	0xc5, 0x4b, 0x4b, 0xad, 0x7c, 0xf0, 0xf2, 0x6c, 0xe1, 0xa2, 0xf3, 0x85, 0x8b, 0x7e, 0x2e, 0x5c,
	0x74, 0xba, 0x74, 0x2b, 0xe7, 0x4b, 0xb7, 0xf2, 0x6d, 0xe9, 0x56, 0xde, 0xf4, 0x12, 0xaa, 0xa7,
	0x59, 0xe8, 0x45, 0x9c, 0xf9, 0x65, 0x31, 0x2e, 0x93, 0xd5, 0x78, 0x97, 0x08, 0xe1, 0x1f, 0x17,
	0x9f, 0x8b, 0x3e, 0x11, 0xa0, 0xc2, 0x9a, 0xb9, 0xd9, 0x0f, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff,
	0x18, 0xec, 0x46, 0x83, 0x1f, 0x05, 0x00, 0x00,
}

func (m *EventDepositToEscrow) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventDepositToEscrow) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventDepositToEscrow) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventWithdrawFromEscrowRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventWithdrawFromEscrowRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventWithdrawFromEscrowRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.AvailableAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.AvailableAt):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintEvent(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x22
	n3, err3 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.RequestedAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.RequestedAt):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintEvent(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventWithdrawFromEscrowExecuted) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventWithdrawFromEscrowExecuted) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventWithdrawFromEscrowExecuted) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventPayForFibre) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventPayForFibre) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventPayForFibre) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Commitment) > 0 {
		i -= len(m.Commitment)
		copy(dAtA[i:], m.Commitment)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Commitment)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Namespace) > 0 {
		i -= len(m.Namespace)
		copy(dAtA[i:], m.Namespace)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Namespace)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventPaymentPromiseTimeout) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventPaymentPromiseTimeout) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventPaymentPromiseTimeout) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PaymentPromiseHash) > 0 {
		i -= len(m.PaymentPromiseHash)
		copy(dAtA[i:], m.PaymentPromiseHash)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.PaymentPromiseHash)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.EscrowSigner) > 0 {
		i -= len(m.EscrowSigner)
		copy(dAtA[i:], m.EscrowSigner)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.EscrowSigner)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Processor) > 0 {
		i -= len(m.Processor)
		copy(dAtA[i:], m.Processor)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Processor)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventUpdateFibreParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventUpdateFibreParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventUpdateFibreParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintEvent(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvent(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EventDepositToEscrow) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovEvent(uint64(l))
	return n
}

func (m *EventWithdrawFromEscrowRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovEvent(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.RequestedAt)
	n += 1 + l + sovEvent(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.AvailableAt)
	n += 1 + l + sovEvent(uint64(l))
	return n
}

func (m *EventWithdrawFromEscrowExecuted) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovEvent(uint64(l))
	return n
}

func (m *EventPayForFibre) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.Namespace)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.Commitment)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	return n
}

func (m *EventPaymentPromiseTimeout) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Processor)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.EscrowSigner)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.PaymentPromiseHash)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	return n
}

func (m *EventUpdateFibreParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovEvent(uint64(l))
	return n
}

func sovEvent(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvent(x uint64) (n int) {
	return sovEvent(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EventDepositToEscrow) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventDepositToEscrow: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventDepositToEscrow: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventWithdrawFromEscrowRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventWithdrawFromEscrowRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventWithdrawFromEscrowRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.RequestedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AvailableAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.AvailableAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventWithdrawFromEscrowExecuted) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventWithdrawFromEscrowExecuted: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventWithdrawFromEscrowExecuted: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventPayForFibre) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventPayForFibre: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventPayForFibre: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Namespace", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Namespace = append(m.Namespace[:0], dAtA[iNdEx:postIndex]...)
			if m.Namespace == nil {
				m.Namespace = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Commitment", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Commitment = append(m.Commitment[:0], dAtA[iNdEx:postIndex]...)
			if m.Commitment == nil {
				m.Commitment = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventPaymentPromiseTimeout) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventPaymentPromiseTimeout: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventPaymentPromiseTimeout: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Processor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Processor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EscrowSigner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EscrowSigner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PaymentPromiseHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PaymentPromiseHash = append(m.PaymentPromiseHash[:0], dAtA[iNdEx:postIndex]...)
			if m.PaymentPromiseHash == nil {
				m.PaymentPromiseHash = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventUpdateFibreParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventUpdateFibreParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventUpdateFibreParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvent(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvent
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvent
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvent
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvent        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvent          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvent = fmt.Errorf("proto: unexpected end of group")
)
