// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: celestia/fibre/v1/fibre.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types1 "github.com/cosmos/cosmos-sdk/codec/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// EscrowAccount helps guarantee payment for a signed PaymentPromise by ensuring
// that a user does not remove funds directly after validators sign over and
// provide service for a blob.
type EscrowAccount struct {
	// signer is the address that controls this escrow account
	Signer string `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	// balance is the total amount currently held in escrow
	Balance types.Coin `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance"`
	// available_balance is the amount available for new payments. This is usually
	// the same as balance except if a user has requested a withdrawal in the past
	// 24 hours in which case available_balance = balance - pending withdrawal
	// amount.
	AvailableBalance types.Coin `protobuf:"bytes,3,opt,name=available_balance,json=availableBalance,proto3" json:"available_balance"`
}

func (m *EscrowAccount) Reset()         { *m = EscrowAccount{} }
func (m *EscrowAccount) String() string { return proto.CompactTextString(m) }
func (*EscrowAccount) ProtoMessage()    {}
func (*EscrowAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a166b9003c3a966, []int{0}
}
func (m *EscrowAccount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EscrowAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EscrowAccount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EscrowAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EscrowAccount.Merge(m, src)
}
func (m *EscrowAccount) XXX_Size() int {
	return m.Size()
}
func (m *EscrowAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_EscrowAccount.DiscardUnknown(m)
}

var xxx_messageInfo_EscrowAccount proto.InternalMessageInfo

func (m *EscrowAccount) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *EscrowAccount) GetBalance() types.Coin {
	if m != nil {
		return m.Balance
	}
	return types.Coin{}
}

func (m *EscrowAccount) GetAvailableBalance() types.Coin {
	if m != nil {
		return m.AvailableBalance
	}
	return types.Coin{}
}

// PaymentPromise is a promise to pay for a fibre blob. It contains the
// commitment and payment details for the fibre blob.
type PaymentPromise struct {
	// chain_id is the chain ID that this payment promise is valid for.
	// Example: arabica-11, mocha-4, or celestia.
	ChainId string `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	// namespace is the namespace the blob is associated with.
	Namespace []byte `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// blob_size is the size of the blob in bytes
	BlobSize uint32 `protobuf:"varint,3,opt,name=blob_size,json=blobSize,proto3" json:"blob_size,omitempty"`
	// commitment is the hash of the row root and the Random Linear Combination (RLC) root
	Commitment []byte `protobuf:"bytes,4,opt,name=commitment,proto3" json:"commitment,omitempty"`
	// row_version is the version of the row format
	RowVersion uint32 `protobuf:"varint,5,opt,name=row_version,json=rowVersion,proto3" json:"row_version,omitempty"`
	// height is the height that is used to determine the validator set that is used
	Height int64 `protobuf:"varint,6,opt,name=height,proto3" json:"height,omitempty"`
	// creation_timestamp is the timestamp when this promise was created. This
	// is critical for determining which validators sign the commitment and
	// determining when service stops for this blob.
	CreationTimestamp time.Time `protobuf:"bytes,7,opt,name=creation_timestamp,json=creationTimestamp,proto3,stdtime" json:"creation_timestamp"`
	// signer_public_key is the public key of the owner of the escrow account to charge
	SignerPublicKey *types1.Any `protobuf:"bytes,8,opt,name=signer_public_key,json=signerPublicKey,proto3" json:"signer_public_key,omitempty"`
	// signature is the signer (escrow account owner) secp256k1 signature over the sign bytes
	Signature []byte `protobuf:"bytes,9,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *PaymentPromise) Reset()         { *m = PaymentPromise{} }
func (m *PaymentPromise) String() string { return proto.CompactTextString(m) }
func (*PaymentPromise) ProtoMessage()    {}
func (*PaymentPromise) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a166b9003c3a966, []int{1}
}
func (m *PaymentPromise) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PaymentPromise) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PaymentPromise.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PaymentPromise) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentPromise.Merge(m, src)
}
func (m *PaymentPromise) XXX_Size() int {
	return m.Size()
}
func (m *PaymentPromise) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentPromise.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentPromise proto.InternalMessageInfo

func (m *PaymentPromise) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *PaymentPromise) GetNamespace() []byte {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *PaymentPromise) GetBlobSize() uint32 {
	if m != nil {
		return m.BlobSize
	}
	return 0
}

func (m *PaymentPromise) GetCommitment() []byte {
	if m != nil {
		return m.Commitment
	}
	return nil
}

func (m *PaymentPromise) GetRowVersion() uint32 {
	if m != nil {
		return m.RowVersion
	}
	return 0
}

func (m *PaymentPromise) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *PaymentPromise) GetCreationTimestamp() time.Time {
	if m != nil {
		return m.CreationTimestamp
	}
	return time.Time{}
}

func (m *PaymentPromise) GetSignerPublicKey() *types1.Any {
	if m != nil {
		return m.SignerPublicKey
	}
	return nil
}

func (m *PaymentPromise) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

// Withdrawal tracks requests to withdraw funds from an escrow account. It is
// needed to implement a delay mechanism between when a withdrawal is requested
// and when it is executed. By default the withdrawal delay is 24 hours.
type Withdrawal struct {
	// signer is the address that owns the escrow account this withdrawal is for
	Signer string `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	// amount is the amount to be withdrawn
	Amount types.Coin `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount"`
	// requested_timestamp is the timestamp when withdrawal was requested
	RequestedTimestamp time.Time `protobuf:"bytes,3,opt,name=requested_timestamp,json=requestedTimestamp,proto3,stdtime" json:"requested_timestamp"`
}

func (m *Withdrawal) Reset()         { *m = Withdrawal{} }
func (m *Withdrawal) String() string { return proto.CompactTextString(m) }
func (*Withdrawal) ProtoMessage()    {}
func (*Withdrawal) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a166b9003c3a966, []int{2}
}
func (m *Withdrawal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Withdrawal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Withdrawal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Withdrawal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Withdrawal.Merge(m, src)
}
func (m *Withdrawal) XXX_Size() int {
	return m.Size()
}
func (m *Withdrawal) XXX_DiscardUnknown() {
	xxx_messageInfo_Withdrawal.DiscardUnknown(m)
}

var xxx_messageInfo_Withdrawal proto.InternalMessageInfo

func (m *Withdrawal) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *Withdrawal) GetAmount() types.Coin {
	if m != nil {
		return m.Amount
	}
	return types.Coin{}
}

func (m *Withdrawal) GetRequestedTimestamp() time.Time {
	if m != nil {
		return m.RequestedTimestamp
	}
	return time.Time{}
}

func init() {
	proto.RegisterType((*EscrowAccount)(nil), "celestia.fibre.v1.EscrowAccount")
	proto.RegisterType((*PaymentPromise)(nil), "celestia.fibre.v1.PaymentPromise")
	proto.RegisterType((*Withdrawal)(nil), "celestia.fibre.v1.Withdrawal")
}

func init() { proto.RegisterFile("celestia/fibre/v1/fibre.proto", fileDescriptor_0a166b9003c3a966) }

var fileDescriptor_0a166b9003c3a966 = []byte{
	// 590 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4f, 0x6f, 0xd3, 0x30,
	0x1c, 0x6d, 0xe8, 0xe8, 0x5a, 0x8f, 0x01, 0x35, 0x13, 0xca, 0x06, 0xa4, 0xd3, 0x4e, 0xbb, 0x2c,
	0xa1, 0x70, 0x40, 0x1c, 0x57, 0xc4, 0x01, 0x8d, 0x43, 0x95, 0xf1, 0x47, 0xda, 0x25, 0xb2, 0xdd,
	0xdf, 0x52, 0x8b, 0xc4, 0x0e, 0xb6, 0xd3, 0x92, 0x7d, 0x08, 0xb4, 0x0f, 0xc3, 0x87, 0x98, 0x76,
	0x40, 0x13, 0x27, 0x4e, 0x80, 0xb6, 0x2f, 0x82, 0x12, 0x27, 0xdd, 0x04, 0x97, 0xc1, 0xcd, 0xbf,
	0xf7, 0xde, 0xef, 0xd9, 0x7e, 0x3f, 0x27, 0xe8, 0x11, 0x83, 0x04, 0xb4, 0xe1, 0x24, 0x38, 0xe4,
	0x54, 0x41, 0x30, 0x1b, 0xda, 0x85, 0x9f, 0x29, 0x69, 0x24, 0xee, 0x37, 0xb4, 0x6f, 0xd1, 0xd9,
	0x70, 0x63, 0x2d, 0x96, 0xb1, 0xac, 0xd8, 0xa0, 0x5c, 0x59, 0xe1, 0x86, 0xc7, 0xa4, 0x4e, 0xa5,
	0x0e, 0x28, 0xd1, 0xa5, 0x09, 0x05, 0x43, 0x86, 0x01, 0x93, 0x5c, 0xd4, 0xfc, 0x20, 0x96, 0x32,
	0x4e, 0x20, 0xa8, 0x2a, 0x9a, 0x1f, 0x06, 0x86, 0xa7, 0xa0, 0x0d, 0x49, 0xb3, 0x5a, 0xb0, 0xfe,
	0xa7, 0x80, 0x88, 0xa2, 0xa1, 0xac, 0x77, 0x64, 0x37, 0xb5, 0x85, 0xa5, 0xb6, 0x4e, 0x1d, 0xb4,
	0xfa, 0x52, 0x33, 0x25, 0xe7, 0xbb, 0x8c, 0xc9, 0x5c, 0x18, 0xfc, 0x18, 0x75, 0x34, 0x8f, 0x05,
	0x28, 0xd7, 0xd9, 0x74, 0xb6, 0x7b, 0x23, 0xf7, 0xdb, 0x97, 0x9d, 0xb5, 0xba, 0x67, 0x77, 0x32,
	0x51, 0xa0, 0xf5, 0xbe, 0x51, 0x5c, 0xc4, 0x61, 0xad, 0xc3, 0xcf, 0xd1, 0x32, 0x25, 0x09, 0x11,
	0x0c, 0xdc, 0x1b, 0x9b, 0xce, 0xf6, 0xca, 0x93, 0x75, 0xbf, 0xd6, 0x97, 0x97, 0xf1, 0xeb, 0xcb,
	0xf8, 0x2f, 0x24, 0x17, 0xa3, 0xa5, 0x93, 0x1f, 0x83, 0x56, 0xd8, 0xe8, 0xf1, 0x6b, 0xd4, 0x27,
	0x33, 0xc2, 0x13, 0x42, 0x13, 0x88, 0x1a, 0x93, 0xf6, 0xf5, 0x4c, 0xee, 0x2e, 0x3a, 0x47, 0xb6,
	0x71, 0xeb, 0x73, 0x1b, 0xdd, 0x1e, 0x93, 0x22, 0x05, 0x61, 0xc6, 0x4a, 0xa6, 0x5c, 0x03, 0x5e,
	0x47, 0x5d, 0x36, 0x25, 0x5c, 0x44, 0x7c, 0x62, 0xef, 0x13, 0x2e, 0x57, 0xf5, 0xab, 0x09, 0x7e,
	0x88, 0x7a, 0x82, 0xa4, 0xa0, 0x33, 0x52, 0x1f, 0xfc, 0x56, 0x78, 0x09, 0xe0, 0x07, 0xa8, 0x47,
	0x13, 0x49, 0x23, 0xcd, 0x8f, 0xec, 0x89, 0x56, 0xc3, 0x6e, 0x09, 0xec, 0xf3, 0x23, 0xc0, 0x1e,
	0x42, 0x4c, 0xa6, 0x29, 0x37, 0xe5, 0x56, 0xee, 0x52, 0xd5, 0x7b, 0x05, 0xc1, 0x03, 0xb4, 0xa2,
	0xe4, 0x3c, 0x9a, 0x81, 0xd2, 0x5c, 0x0a, 0xf7, 0x66, 0xd5, 0x8e, 0x94, 0x9c, 0xbf, 0xb3, 0x08,
	0xbe, 0x8f, 0x3a, 0x53, 0xe0, 0xf1, 0xd4, 0xb8, 0x9d, 0x4d, 0x67, 0xbb, 0x1d, 0xd6, 0x15, 0xde,
	0x47, 0x98, 0x29, 0x20, 0x86, 0x4b, 0x11, 0x2d, 0x06, 0xec, 0x2e, 0x57, 0x81, 0x6c, 0xf8, 0x76,
	0xc2, 0x7e, 0x33, 0x61, 0xff, 0x4d, 0xa3, 0x18, 0x75, 0xcb, 0x44, 0x8e, 0x7f, 0x0e, 0x9c, 0xb0,
	0xdf, 0xf4, 0x2f, 0x48, 0x7c, 0x80, 0xfa, 0x76, 0x52, 0x51, 0x96, 0xd3, 0x84, 0xb3, 0xe8, 0x03,
	0x14, 0x6e, 0xb7, 0xf2, 0x5c, 0xfb, 0xcb, 0x73, 0x57, 0x14, 0x23, 0xf7, 0xf4, 0x72, 0xe4, 0x4c,
	0x15, 0x99, 0x91, 0xfe, 0x38, 0xa7, 0x7b, 0x50, 0x84, 0x77, 0xac, 0xd1, 0xb8, 0xf2, 0xd9, 0x83,
	0xa2, 0x0c, 0xb1, 0x84, 0x88, 0xc9, 0x15, 0xb8, 0x3d, 0x1b, 0xe2, 0x02, 0xd8, 0xfa, 0xea, 0x20,
	0xf4, 0x9e, 0x9b, 0xe9, 0x44, 0x91, 0x39, 0x49, 0xfe, 0xe3, 0x69, 0x3d, 0x43, 0x1d, 0x92, 0x96,
	0xcf, 0xf2, 0xba, 0x2f, 0xab, 0x96, 0xe3, 0xb7, 0xe8, 0x9e, 0x82, 0x8f, 0x39, 0x68, 0x03, 0x93,
	0x2b, 0x49, 0xb6, 0xff, 0x21, 0x49, 0xbc, 0x30, 0xb8, 0x64, 0xf7, 0x4e, 0xce, 0x3d, 0xe7, 0xec,
	0xdc, 0x73, 0x7e, 0x9d, 0x7b, 0xce, 0xf1, 0x85, 0xd7, 0x3a, 0xbb, 0xf0, 0x5a, 0xdf, 0x2f, 0xbc,
	0xd6, 0xc1, 0x30, 0xe6, 0x66, 0x9a, 0x53, 0x9f, 0xc9, 0x34, 0x68, 0xbe, 0x79, 0xa9, 0xe2, 0xc5,
	0x7a, 0x87, 0x64, 0x59, 0xf0, 0xa9, 0xfe, 0x49, 0x98, 0x22, 0x03, 0x4d, 0x3b, 0xd5, 0xf6, 0x4f,
	0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0xb6, 0x76, 0xf3, 0xa6, 0x43, 0x04, 0x00, 0x00,
}

func (m *EscrowAccount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EscrowAccount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EscrowAccount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.AvailableBalance.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintFibre(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.Balance.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintFibre(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintFibre(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PaymentPromise) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PaymentPromise) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PaymentPromise) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintFibre(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x4a
	}
	if m.SignerPublicKey != nil {
		{
			size, err := m.SignerPublicKey.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintFibre(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x42
	}
	n4, err4 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.CreationTimestamp, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.CreationTimestamp):])
	if err4 != nil {
		return 0, err4
	}
	i -= n4
	i = encodeVarintFibre(dAtA, i, uint64(n4))
	i--
	dAtA[i] = 0x3a
	if m.Height != 0 {
		i = encodeVarintFibre(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x30
	}
	if m.RowVersion != 0 {
		i = encodeVarintFibre(dAtA, i, uint64(m.RowVersion))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Commitment) > 0 {
		i -= len(m.Commitment)
		copy(dAtA[i:], m.Commitment)
		i = encodeVarintFibre(dAtA, i, uint64(len(m.Commitment)))
		i--
		dAtA[i] = 0x22
	}
	if m.BlobSize != 0 {
		i = encodeVarintFibre(dAtA, i, uint64(m.BlobSize))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Namespace) > 0 {
		i -= len(m.Namespace)
		copy(dAtA[i:], m.Namespace)
		i = encodeVarintFibre(dAtA, i, uint64(len(m.Namespace)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintFibre(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Withdrawal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Withdrawal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Withdrawal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n5, err5 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.RequestedTimestamp, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.RequestedTimestamp):])
	if err5 != nil {
		return 0, err5
	}
	i -= n5
	i = encodeVarintFibre(dAtA, i, uint64(n5))
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintFibre(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintFibre(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintFibre(dAtA []byte, offset int, v uint64) int {
	offset -= sovFibre(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EscrowAccount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovFibre(uint64(l))
	}
	l = m.Balance.Size()
	n += 1 + l + sovFibre(uint64(l))
	l = m.AvailableBalance.Size()
	n += 1 + l + sovFibre(uint64(l))
	return n
}

func (m *PaymentPromise) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovFibre(uint64(l))
	}
	l = len(m.Namespace)
	if l > 0 {
		n += 1 + l + sovFibre(uint64(l))
	}
	if m.BlobSize != 0 {
		n += 1 + sovFibre(uint64(m.BlobSize))
	}
	l = len(m.Commitment)
	if l > 0 {
		n += 1 + l + sovFibre(uint64(l))
	}
	if m.RowVersion != 0 {
		n += 1 + sovFibre(uint64(m.RowVersion))
	}
	if m.Height != 0 {
		n += 1 + sovFibre(uint64(m.Height))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.CreationTimestamp)
	n += 1 + l + sovFibre(uint64(l))
	if m.SignerPublicKey != nil {
		l = m.SignerPublicKey.Size()
		n += 1 + l + sovFibre(uint64(l))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovFibre(uint64(l))
	}
	return n
}

func (m *Withdrawal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovFibre(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovFibre(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.RequestedTimestamp)
	n += 1 + l + sovFibre(uint64(l))
	return n
}

func sovFibre(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozFibre(x uint64) (n int) {
	return sovFibre(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EscrowAccount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFibre
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EscrowAccount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EscrowAccount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFibre
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFibre
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFibre
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Balance", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFibre
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFibre
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFibre
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Balance.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AvailableBalance", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFibre
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFibre
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFibre
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AvailableBalance.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFibre(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFibre
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PaymentPromise) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFibre
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PaymentPromise: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PaymentPromise: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFibre
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFibre
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFibre
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Namespace", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFibre
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthFibre
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthFibre
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Namespace = append(m.Namespace[:0], dAtA[iNdEx:postIndex]...)
			if m.Namespace == nil {
				m.Namespace = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlobSize", wireType)
			}
			m.BlobSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFibre
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlobSize |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Commitment", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFibre
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthFibre
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthFibre
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Commitment = append(m.Commitment[:0], dAtA[iNdEx:postIndex]...)
			if m.Commitment == nil {
				m.Commitment = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RowVersion", wireType)
			}
			m.RowVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFibre
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RowVersion |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFibre
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreationTimestamp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFibre
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFibre
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFibre
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.CreationTimestamp, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignerPublicKey", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFibre
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFibre
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFibre
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.SignerPublicKey == nil {
				m.SignerPublicKey = &types1.Any{}
			}
			if err := m.SignerPublicKey.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFibre
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthFibre
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthFibre
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFibre(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFibre
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Withdrawal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFibre
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Withdrawal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Withdrawal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFibre
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFibre
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFibre
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFibre
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFibre
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFibre
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestedTimestamp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFibre
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFibre
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFibre
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.RequestedTimestamp, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFibre(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFibre
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipFibre(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowFibre
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFibre
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFibre
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthFibre
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupFibre
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthFibre
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthFibre        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowFibre          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupFibre = fmt.Errorf("proto: unexpected end of group")
)
