// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: celestia/fibre/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the fibre module's genesis state.
type GenesisState struct {
	Params                Params                `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	EscrowAccounts        []EscrowAccount       `protobuf:"bytes,2,rep,name=escrow_accounts,json=escrowAccounts,proto3" json:"escrow_accounts"`
	Withdrawals           []Withdrawal          `protobuf:"bytes,3,rep,name=withdrawals,proto3" json:"withdrawals"`
	PaymentPromiseEntries []PaymentPromiseEntry `protobuf:"bytes,4,rep,name=payment_promise_entries,json=paymentPromiseEntries,proto3" json:"payment_promise_entries"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1ca2219340f8f50, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetEscrowAccounts() []EscrowAccount {
	if m != nil {
		return m.EscrowAccounts
	}
	return nil
}

func (m *GenesisState) GetWithdrawals() []Withdrawal {
	if m != nil {
		return m.Withdrawals
	}
	return nil
}

func (m *GenesisState) GetPaymentPromiseEntries() []PaymentPromiseEntry {
	if m != nil {
		return m.PaymentPromiseEntries
	}
	return nil
}

// PaymentPromiseEntry represents a processed PaymentPromise in genesis state.
// PaymentPromiseEntry intentionally omits many fields from the original
// PaymentPromise to avoid bloading the state.
type PaymentPromiseEntry struct {
	PaymentPromiseHash []byte    `protobuf:"bytes,1,opt,name=payment_promise_hash,json=paymentPromiseHash,proto3" json:"payment_promise_hash,omitempty"`
	ProcessedAt        time.Time `protobuf:"bytes,2,opt,name=processed_at,json=processedAt,proto3,stdtime" json:"processed_at"`
}

func (m *PaymentPromiseEntry) Reset()         { *m = PaymentPromiseEntry{} }
func (m *PaymentPromiseEntry) String() string { return proto.CompactTextString(m) }
func (*PaymentPromiseEntry) ProtoMessage()    {}
func (*PaymentPromiseEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1ca2219340f8f50, []int{1}
}
func (m *PaymentPromiseEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PaymentPromiseEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PaymentPromiseEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PaymentPromiseEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentPromiseEntry.Merge(m, src)
}
func (m *PaymentPromiseEntry) XXX_Size() int {
	return m.Size()
}
func (m *PaymentPromiseEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentPromiseEntry.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentPromiseEntry proto.InternalMessageInfo

func (m *PaymentPromiseEntry) GetPaymentPromiseHash() []byte {
	if m != nil {
		return m.PaymentPromiseHash
	}
	return nil
}

func (m *PaymentPromiseEntry) GetProcessedAt() time.Time {
	if m != nil {
		return m.ProcessedAt
	}
	return time.Time{}
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "celestia.fibre.v1.GenesisState")
	proto.RegisterType((*PaymentPromiseEntry)(nil), "celestia.fibre.v1.PaymentPromiseEntry")
}

func init() { proto.RegisterFile("celestia/fibre/v1/genesis.proto", fileDescriptor_f1ca2219340f8f50) }

var fileDescriptor_f1ca2219340f8f50 = []byte{
	// 416 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x41, 0x6b, 0xdb, 0x30,
	0x14, 0xc7, 0xe3, 0xb4, 0x94, 0xa1, 0x84, 0x8d, 0x69, 0x1d, 0xf3, 0x02, 0x75, 0x42, 0x0f, 0xa3,
	0x97, 0x49, 0x4b, 0x77, 0xd8, 0xb9, 0x81, 0xd0, 0xc1, 0x0e, 0x2b, 0xd9, 0x60, 0xb0, 0x8b, 0x91,
	0x9d, 0x57, 0x5b, 0x10, 0x5b, 0x42, 0x4f, 0x69, 0x96, 0x6f, 0x91, 0x2f, 0x35, 0xe8, 0xb1, 0xc7,
	0x9d, 0xb6, 0x91, 0x7c, 0x91, 0x51, 0xc9, 0x0e, 0x5d, 0xed, 0x9b, 0xec, 0xf7, 0xfb, 0xff, 0xde,
	0x93, 0x9f, 0xc9, 0x30, 0x85, 0x05, 0xa0, 0x95, 0x82, 0x5f, 0xcb, 0xc4, 0x00, 0xbf, 0x19, 0xf3,
	0x0c, 0x4a, 0x40, 0x89, 0x4c, 0x1b, 0x65, 0x15, 0x7d, 0x5e, 0x03, 0xcc, 0x01, 0xec, 0x66, 0x3c,
	0x38, 0xce, 0x54, 0xa6, 0x5c, 0x95, 0xdf, 0x9f, 0x3c, 0x38, 0x88, 0x9a, 0x26, 0x2d, 0x8c, 0x28,
	0x2a, 0xd1, 0xe0, 0xa4, 0x59, 0xf7, 0x46, 0x5f, 0x1e, 0x66, 0x4a, 0x65, 0x0b, 0xe0, 0xee, 0x29,
	0x59, 0x5e, 0x73, 0x2b, 0x0b, 0x40, 0x2b, 0x0a, 0xed, 0x81, 0xd3, 0x9f, 0x5d, 0xd2, 0xbf, 0xf4,
	0xa3, 0x7d, 0xb1, 0xc2, 0x02, 0xfd, 0x40, 0x8e, 0x7c, 0x83, 0x30, 0x18, 0x05, 0x67, 0xbd, 0xf3,
	0xd7, 0xac, 0x31, 0x2a, 0xbb, 0x72, 0xc0, 0xe4, 0xf0, 0xf6, 0xf7, 0xb0, 0x33, 0xab, 0x70, 0xfa,
	0x99, 0x3c, 0x03, 0x4c, 0x8d, 0x5a, 0xc5, 0x22, 0x4d, 0xd5, 0xb2, 0xb4, 0x18, 0x76, 0x47, 0x07,
	0x67, 0xbd, 0xf3, 0x51, 0x8b, 0x61, 0xea, 0xc8, 0x0b, 0x0f, 0x56, 0xa2, 0xa7, 0xf0, 0xf0, 0x25,
	0xd2, 0x29, 0xe9, 0xad, 0xa4, 0xcd, 0xe7, 0x46, 0xac, 0xc4, 0x02, 0xc3, 0x03, 0x27, 0x3b, 0x69,
	0x91, 0x7d, 0xdb, 0x53, 0x95, 0xe9, 0x61, 0x8e, 0xce, 0xc9, 0x2b, 0x2d, 0xd6, 0x05, 0x94, 0x36,
	0xd6, 0x46, 0x15, 0x12, 0x21, 0x86, 0xd2, 0x1a, 0x09, 0x18, 0x1e, 0x3a, 0xe5, 0x9b, 0xd6, 0x1b,
	0xba, 0xc4, 0x95, 0x0f, 0x4c, 0x4b, 0x6b, 0xd6, 0x95, 0xfb, 0xa5, 0x6e, 0x94, 0x24, 0xe0, 0xe9,
	0x26, 0x20, 0x2f, 0x5a, 0x42, 0xf4, 0x1d, 0x39, 0x7e, 0xdc, 0x3d, 0x17, 0x98, 0xbb, 0x8f, 0xdb,
	0x9f, 0xd1, 0xff, 0x65, 0x1f, 0x05, 0xe6, 0xf4, 0x92, 0xf4, 0xb5, 0x51, 0x29, 0x20, 0xc2, 0x3c,
	0x16, 0x36, 0xec, 0xba, 0x35, 0x0c, 0x98, 0xdf, 0x24, 0xab, 0x37, 0xc9, 0xbe, 0xd6, 0x9b, 0x9c,
	0x3c, 0xb9, 0x1f, 0x6c, 0xf3, 0x67, 0x18, 0xcc, 0x7a, 0xfb, 0xe4, 0x85, 0x9d, 0x7c, 0xba, 0xdd,
	0x46, 0xc1, 0xdd, 0x36, 0x0a, 0xfe, 0x6e, 0xa3, 0x60, 0xb3, 0x8b, 0x3a, 0x77, 0xbb, 0xa8, 0xf3,
	0x6b, 0x17, 0x75, 0xbe, 0x8f, 0x33, 0x69, 0xf3, 0x65, 0xc2, 0x52, 0x55, 0xf0, 0xfa, 0xee, 0xca,
	0x64, 0xfb, 0xf3, 0x5b, 0xa1, 0x35, 0xff, 0x51, 0xfd, 0x51, 0x76, 0xad, 0x01, 0x93, 0x23, 0xd7,
	0xf7, 0xfd, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9a, 0x8d, 0xfd, 0xc6, 0xda, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PaymentPromiseEntries) > 0 {
		for iNdEx := len(m.PaymentPromiseEntries) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PaymentPromiseEntries[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Withdrawals) > 0 {
		for iNdEx := len(m.Withdrawals) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Withdrawals[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.EscrowAccounts) > 0 {
		for iNdEx := len(m.EscrowAccounts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.EscrowAccounts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *PaymentPromiseEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PaymentPromiseEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PaymentPromiseEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.ProcessedAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.ProcessedAt):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintGenesis(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x12
	if len(m.PaymentPromiseHash) > 0 {
		i -= len(m.PaymentPromiseHash)
		copy(dAtA[i:], m.PaymentPromiseHash)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.PaymentPromiseHash)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.EscrowAccounts) > 0 {
		for _, e := range m.EscrowAccounts {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Withdrawals) > 0 {
		for _, e := range m.Withdrawals {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.PaymentPromiseEntries) > 0 {
		for _, e := range m.PaymentPromiseEntries {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *PaymentPromiseEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PaymentPromiseHash)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.ProcessedAt)
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EscrowAccounts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EscrowAccounts = append(m.EscrowAccounts, EscrowAccount{})
			if err := m.EscrowAccounts[len(m.EscrowAccounts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Withdrawals", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Withdrawals = append(m.Withdrawals, Withdrawal{})
			if err := m.Withdrawals[len(m.Withdrawals)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PaymentPromiseEntries", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PaymentPromiseEntries = append(m.PaymentPromiseEntries, PaymentPromiseEntry{})
			if err := m.PaymentPromiseEntries[len(m.PaymentPromiseEntries)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PaymentPromiseEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PaymentPromiseEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PaymentPromiseEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PaymentPromiseHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PaymentPromiseHash = append(m.PaymentPromiseHash[:0], dAtA[iNdEx:postIndex]...)
			if m.PaymentPromiseHash == nil {
				m.PaymentPromiseHash = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProcessedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.ProcessedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
