// Code generated by protoc-gen-go-drpc. DO NOT EDIT.
// protoc-gen-go-drpc version: v0.0.34
// source: celestia/fibre/v1/service.proto

package types

import (
	bytes "bytes"
	context "context"
	errors "errors"
	jsonpb "github.com/gogo/protobuf/jsonpb"
	proto "github.com/gogo/protobuf/proto"
	drpc "storj.io/drpc"
	drpcerr "storj.io/drpc/drpcerr"
)

type drpcEncoding_File_celestia_fibre_v1_service_proto struct{}

func (drpcEncoding_File_celestia_fibre_v1_service_proto) Marshal(msg drpc.Message) ([]byte, error) {
	return proto.Marshal(msg.(proto.Message))
}

func (drpcEncoding_File_celestia_fibre_v1_service_proto) Unmarshal(buf []byte, msg drpc.Message) error {
	return proto.Unmarshal(buf, msg.(proto.Message))
}

func (drpcEncoding_File_celestia_fibre_v1_service_proto) JSONMarshal(msg drpc.Message) ([]byte, error) {
	var buf bytes.Buffer
	err := new(jsonpb.Marshaler).Marshal(&buf, msg.(proto.Message))
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func (drpcEncoding_File_celestia_fibre_v1_service_proto) JSONUnmarshal(buf []byte, msg drpc.Message) error {
	return jsonpb.Unmarshal(bytes.NewReader(buf), msg.(proto.Message))
}

type DRPCFibreClient interface {
	DRPCConn() drpc.Conn

	UploadRows(ctx context.Context, in *UploadRowsRequest) (*UploadRowsResponse, error)
	DownloadRows(ctx context.Context, in *DownloadRowsRequest) (*DownloadRowsResponse, error)
}

type drpcFibreClient struct {
	cc drpc.Conn
}

func NewDRPCFibreClient(cc drpc.Conn) DRPCFibreClient {
	return &drpcFibreClient{cc}
}

func (c *drpcFibreClient) DRPCConn() drpc.Conn { return c.cc }

func (c *drpcFibreClient) UploadRows(ctx context.Context, in *UploadRowsRequest) (*UploadRowsResponse, error) {
	out := new(UploadRowsResponse)
	err := c.cc.Invoke(ctx, "/celestia.fibre.v1.Fibre/UploadRows", drpcEncoding_File_celestia_fibre_v1_service_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drpcFibreClient) DownloadRows(ctx context.Context, in *DownloadRowsRequest) (*DownloadRowsResponse, error) {
	out := new(DownloadRowsResponse)
	err := c.cc.Invoke(ctx, "/celestia.fibre.v1.Fibre/DownloadRows", drpcEncoding_File_celestia_fibre_v1_service_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type DRPCFibreServer interface {
	UploadRows(context.Context, *UploadRowsRequest) (*UploadRowsResponse, error)
	DownloadRows(context.Context, *DownloadRowsRequest) (*DownloadRowsResponse, error)
}

type DRPCFibreUnimplementedServer struct{}

func (s *DRPCFibreUnimplementedServer) UploadRows(context.Context, *UploadRowsRequest) (*UploadRowsResponse, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCFibreUnimplementedServer) DownloadRows(context.Context, *DownloadRowsRequest) (*DownloadRowsResponse, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

type DRPCFibreDescription struct{}

func (DRPCFibreDescription) NumMethods() int { return 2 }

func (DRPCFibreDescription) Method(n int) (string, drpc.Encoding, drpc.Receiver, interface{}, bool) {
	switch n {
	case 0:
		return "/celestia.fibre.v1.Fibre/UploadRows", drpcEncoding_File_celestia_fibre_v1_service_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCFibreServer).
					UploadRows(
						ctx,
						in1.(*UploadRowsRequest),
					)
			}, DRPCFibreServer.UploadRows, true
	case 1:
		return "/celestia.fibre.v1.Fibre/DownloadRows", drpcEncoding_File_celestia_fibre_v1_service_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCFibreServer).
					DownloadRows(
						ctx,
						in1.(*DownloadRowsRequest),
					)
			}, DRPCFibreServer.DownloadRows, true
	default:
		return "", nil, nil, nil, false
	}
}

func DRPCRegisterFibre(mux drpc.Mux, impl DRPCFibreServer) error {
	return mux.Register(impl, DRPCFibreDescription{})
}

type DRPCFibre_UploadRowsStream interface {
	drpc.Stream
	SendAndClose(*UploadRowsResponse) error
}

type drpcFibre_UploadRowsStream struct {
	drpc.Stream
}

func (x *drpcFibre_UploadRowsStream) SendAndClose(m *UploadRowsResponse) error {
	if err := x.MsgSend(m, drpcEncoding_File_celestia_fibre_v1_service_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}

type DRPCFibre_DownloadRowsStream interface {
	drpc.Stream
	SendAndClose(*DownloadRowsResponse) error
}

type drpcFibre_DownloadRowsStream struct {
	drpc.Stream
}

func (x *drpcFibre_DownloadRowsStream) SendAndClose(m *DownloadRowsResponse) error {
	if err := x.MsgSend(m, drpcEncoding_File_celestia_fibre_v1_service_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}
