// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: celestia/fibre/v1/service.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Row struct {
	Index uint32   `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Data  []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Proof [][]byte `protobuf:"bytes,3,rep,name=proof,proto3" json:"proof,omitempty"`
}

func (m *Row) Reset()         { *m = Row{} }
func (m *Row) String() string { return proto.CompactTextString(m) }
func (*Row) ProtoMessage()    {}
func (*Row) Descriptor() ([]byte, []int) {
	return fileDescriptor_15ef7a812f3b6799, []int{0}
}
func (m *Row) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Row) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Row.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Row) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Row.Merge(m, src)
}
func (m *Row) XXX_Size() int {
	return m.Size()
}
func (m *Row) XXX_DiscardUnknown() {
	xxx_messageInfo_Row.DiscardUnknown(m)
}

var xxx_messageInfo_Row proto.InternalMessageInfo

func (m *Row) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Row) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Row) GetProof() [][]byte {
	if m != nil {
		return m.Proof
	}
	return nil
}

type Rows struct {
	Rows []*Row `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	// Types that are valid to be assigned to Rlc:
	//	*Rows_Coefficients
	//	*Rows_Root
	Rlc isRows_Rlc `protobuf_oneof:"rlc"`
}

func (m *Rows) Reset()         { *m = Rows{} }
func (m *Rows) String() string { return proto.CompactTextString(m) }
func (*Rows) ProtoMessage()    {}
func (*Rows) Descriptor() ([]byte, []int) {
	return fileDescriptor_15ef7a812f3b6799, []int{1}
}
func (m *Rows) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Rows) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Rows.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Rows) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rows.Merge(m, src)
}
func (m *Rows) XXX_Size() int {
	return m.Size()
}
func (m *Rows) XXX_DiscardUnknown() {
	xxx_messageInfo_Rows.DiscardUnknown(m)
}

var xxx_messageInfo_Rows proto.InternalMessageInfo

type isRows_Rlc interface {
	isRows_Rlc()
	MarshalTo([]byte) (int, error)
	Size() int
}

type Rows_Coefficients struct {
	Coefficients []byte `protobuf:"bytes,2,opt,name=coefficients,proto3,oneof" json:"coefficients,omitempty"`
}
type Rows_Root struct {
	Root []byte `protobuf:"bytes,3,opt,name=root,proto3,oneof" json:"root,omitempty"`
}

func (*Rows_Coefficients) isRows_Rlc() {}
func (*Rows_Root) isRows_Rlc()         {}

func (m *Rows) GetRlc() isRows_Rlc {
	if m != nil {
		return m.Rlc
	}
	return nil
}

func (m *Rows) GetRows() []*Row {
	if m != nil {
		return m.Rows
	}
	return nil
}

func (m *Rows) GetCoefficients() []byte {
	if x, ok := m.GetRlc().(*Rows_Coefficients); ok {
		return x.Coefficients
	}
	return nil
}

func (m *Rows) GetRoot() []byte {
	if x, ok := m.GetRlc().(*Rows_Root); ok {
		return x.Root
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Rows) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Rows_Coefficients)(nil),
		(*Rows_Root)(nil),
	}
}

type UploadRowsRequest struct {
	Promise *PaymentPromise `protobuf:"bytes,1,opt,name=promise,proto3" json:"promise,omitempty"`
	Rows    *Rows           `protobuf:"bytes,2,opt,name=rows,proto3" json:"rows,omitempty"`
}

func (m *UploadRowsRequest) Reset()         { *m = UploadRowsRequest{} }
func (m *UploadRowsRequest) String() string { return proto.CompactTextString(m) }
func (*UploadRowsRequest) ProtoMessage()    {}
func (*UploadRowsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15ef7a812f3b6799, []int{2}
}
func (m *UploadRowsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UploadRowsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UploadRowsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UploadRowsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadRowsRequest.Merge(m, src)
}
func (m *UploadRowsRequest) XXX_Size() int {
	return m.Size()
}
func (m *UploadRowsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadRowsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadRowsRequest proto.InternalMessageInfo

func (m *UploadRowsRequest) GetPromise() *PaymentPromise {
	if m != nil {
		return m.Promise
	}
	return nil
}

func (m *UploadRowsRequest) GetRows() *Rows {
	if m != nil {
		return m.Rows
	}
	return nil
}

type UploadRowsResponse struct {
	ValidatorSignature []byte `protobuf:"bytes,1,opt,name=validator_signature,json=validatorSignature,proto3" json:"validator_signature,omitempty"`
}

func (m *UploadRowsResponse) Reset()         { *m = UploadRowsResponse{} }
func (m *UploadRowsResponse) String() string { return proto.CompactTextString(m) }
func (*UploadRowsResponse) ProtoMessage()    {}
func (*UploadRowsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_15ef7a812f3b6799, []int{3}
}
func (m *UploadRowsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UploadRowsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UploadRowsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UploadRowsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadRowsResponse.Merge(m, src)
}
func (m *UploadRowsResponse) XXX_Size() int {
	return m.Size()
}
func (m *UploadRowsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadRowsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadRowsResponse proto.InternalMessageInfo

func (m *UploadRowsResponse) GetValidatorSignature() []byte {
	if m != nil {
		return m.ValidatorSignature
	}
	return nil
}

type DownloadRowsRequest struct {
	Commitment []byte `protobuf:"bytes,1,opt,name=commitment,proto3" json:"commitment,omitempty"`
}

func (m *DownloadRowsRequest) Reset()         { *m = DownloadRowsRequest{} }
func (m *DownloadRowsRequest) String() string { return proto.CompactTextString(m) }
func (*DownloadRowsRequest) ProtoMessage()    {}
func (*DownloadRowsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15ef7a812f3b6799, []int{4}
}
func (m *DownloadRowsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DownloadRowsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DownloadRowsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DownloadRowsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadRowsRequest.Merge(m, src)
}
func (m *DownloadRowsRequest) XXX_Size() int {
	return m.Size()
}
func (m *DownloadRowsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadRowsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadRowsRequest proto.InternalMessageInfo

func (m *DownloadRowsRequest) GetCommitment() []byte {
	if m != nil {
		return m.Commitment
	}
	return nil
}

type DownloadRowsResponse struct {
	Rows *Rows `protobuf:"bytes,1,opt,name=rows,proto3" json:"rows,omitempty"`
}

func (m *DownloadRowsResponse) Reset()         { *m = DownloadRowsResponse{} }
func (m *DownloadRowsResponse) String() string { return proto.CompactTextString(m) }
func (*DownloadRowsResponse) ProtoMessage()    {}
func (*DownloadRowsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_15ef7a812f3b6799, []int{5}
}
func (m *DownloadRowsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DownloadRowsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DownloadRowsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DownloadRowsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadRowsResponse.Merge(m, src)
}
func (m *DownloadRowsResponse) XXX_Size() int {
	return m.Size()
}
func (m *DownloadRowsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadRowsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadRowsResponse proto.InternalMessageInfo

func (m *DownloadRowsResponse) GetRows() *Rows {
	if m != nil {
		return m.Rows
	}
	return nil
}

func init() {
	proto.RegisterType((*Row)(nil), "celestia.fibre.v1.Row")
	proto.RegisterType((*Rows)(nil), "celestia.fibre.v1.Rows")
	proto.RegisterType((*UploadRowsRequest)(nil), "celestia.fibre.v1.UploadRowsRequest")
	proto.RegisterType((*UploadRowsResponse)(nil), "celestia.fibre.v1.UploadRowsResponse")
	proto.RegisterType((*DownloadRowsRequest)(nil), "celestia.fibre.v1.DownloadRowsRequest")
	proto.RegisterType((*DownloadRowsResponse)(nil), "celestia.fibre.v1.DownloadRowsResponse")
}

func init() { proto.RegisterFile("celestia/fibre/v1/service.proto", fileDescriptor_15ef7a812f3b6799) }

var fileDescriptor_15ef7a812f3b6799 = []byte{
	// 448 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0x6e, 0x96, 0x16, 0xa4, 0xb7, 0x70, 0x98, 0x57, 0x41, 0x54, 0x89, 0x50, 0xa2, 0x01, 0x15,
	0x13, 0x89, 0x5a, 0xc4, 0x89, 0xdb, 0x60, 0x08, 0x89, 0xcb, 0x64, 0xc4, 0x01, 0x2e, 0x93, 0x9b,
	0xba, 0xc5, 0x52, 0x93, 0x17, 0x6c, 0xb7, 0xd9, 0x0e, 0xfc, 0x07, 0xfe, 0x13, 0x17, 0x8e, 0x3b,
	0x72, 0x44, 0xed, 0x1f, 0x41, 0xb1, 0x93, 0xd2, 0xd1, 0x48, 0xbd, 0xf9, 0xbd, 0xf7, 0x7d, 0xfe,
	0xbe, 0xcf, 0xd6, 0x83, 0x47, 0x09, 0x9f, 0x73, 0xa5, 0x05, 0x8b, 0xa7, 0x62, 0x2c, 0x79, 0xbc,
	0x1c, 0xc6, 0x8a, 0xcb, 0xa5, 0x48, 0x78, 0x94, 0x4b, 0xd4, 0x48, 0x8e, 0x6a, 0x40, 0x64, 0x00,
	0xd1, 0x72, 0xd8, 0x7b, 0xb8, 0xcb, 0xb1, 0x33, 0xc3, 0x08, 0xcf, 0xc1, 0xa5, 0x58, 0x90, 0x2e,
	0x74, 0x44, 0x36, 0xe1, 0x57, 0xbe, 0xd3, 0x77, 0x06, 0xf7, 0xa8, 0x2d, 0x08, 0x81, 0xf6, 0x84,
	0x69, 0xe6, 0x1f, 0xf4, 0x9d, 0x81, 0x47, 0xcd, 0xb9, 0x44, 0xe6, 0x12, 0x71, 0xea, 0xbb, 0x7d,
	0x77, 0xe0, 0x51, 0x5b, 0x84, 0x0b, 0x68, 0x53, 0x2c, 0x14, 0x79, 0x0e, 0x6d, 0x89, 0x85, 0xf2,
	0x9d, 0xbe, 0x3b, 0x38, 0x1c, 0xdd, 0x8f, 0x76, 0xfc, 0x44, 0x14, 0x0b, 0x6a, 0x30, 0xe4, 0x04,
	0xbc, 0x04, 0xf9, 0x74, 0x2a, 0x12, 0xc1, 0x33, 0xad, 0xac, 0xca, 0xfb, 0x16, 0xbd, 0xd5, 0x25,
	0xdd, 0xf2, 0x46, 0xd4, 0xbe, 0x5b, 0x4d, 0x4d, 0x75, 0xd6, 0x01, 0x57, 0xce, 0x93, 0xf0, 0x3b,
	0x1c, 0x7d, 0xca, 0xe7, 0xc8, 0x26, 0xa5, 0x38, 0xe5, 0xdf, 0x16, 0x5c, 0x69, 0xf2, 0x1a, 0xee,
	0xe6, 0x12, 0x53, 0xa1, 0xb8, 0x49, 0x73, 0x38, 0x7a, 0xdc, 0x60, 0xe3, 0x82, 0x5d, 0xa7, 0x3c,
	0xd3, 0x17, 0x16, 0x48, 0x6b, 0x06, 0x39, 0xad, 0x02, 0x1c, 0x18, 0xe6, 0x83, 0xe6, 0x00, 0xca,
	0x26, 0x08, 0xcf, 0x81, 0x6c, 0xcb, 0xab, 0x1c, 0x33, 0xc5, 0x49, 0x0c, 0xc7, 0x4b, 0x36, 0x17,
	0x13, 0xa6, 0x51, 0x5e, 0x2a, 0x31, 0xcb, 0x98, 0x5e, 0x48, 0xeb, 0xc5, 0xa3, 0x64, 0x33, 0xfa,
	0x58, 0x4f, 0xc2, 0x57, 0x70, 0xfc, 0x16, 0x8b, 0xec, 0xff, 0x1c, 0x01, 0x40, 0x82, 0x69, 0x2a,
	0x74, 0x69, 0xb4, 0xa2, 0x6f, 0x75, 0xc2, 0x37, 0xd0, 0xbd, 0x4d, 0xab, 0xf4, 0x4f, 0x37, 0x7f,
	0xb0, 0x3f, 0xc2, 0xe8, 0xa7, 0x03, 0x9d, 0x77, 0x65, 0x9f, 0x7c, 0x06, 0xf8, 0x17, 0x86, 0x9c,
	0x34, 0xd0, 0x76, 0x9e, 0xba, 0xf7, 0x64, 0x0f, 0xaa, 0x72, 0x74, 0x09, 0xde, 0xb6, 0x53, 0xf2,
	0xb4, 0x81, 0xd6, 0xf0, 0x02, 0xbd, 0x67, 0x7b, 0x71, 0x56, 0xe0, 0xec, 0xc3, 0xaf, 0x55, 0xe0,
	0xdc, 0xac, 0x02, 0xe7, 0xcf, 0x2a, 0x70, 0x7e, 0xac, 0x83, 0xd6, 0xcd, 0x3a, 0x68, 0xfd, 0x5e,
	0x07, 0xad, 0x2f, 0xc3, 0x99, 0xd0, 0x5f, 0x17, 0xe3, 0x28, 0xc1, 0x34, 0xae, 0x2f, 0x43, 0x39,
	0xdb, 0x9c, 0x5f, 0xb0, 0x3c, 0x8f, 0xaf, 0xaa, 0xdd, 0xd0, 0xd7, 0x39, 0x57, 0xe3, 0x3b, 0x66,
	0x33, 0x5e, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x43, 0x7d, 0x6c, 0x7f, 0x6e, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FibreClient is the client API for Fibre service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FibreClient interface {
	UploadRows(ctx context.Context, in *UploadRowsRequest, opts ...grpc.CallOption) (*UploadRowsResponse, error)
	DownloadRows(ctx context.Context, in *DownloadRowsRequest, opts ...grpc.CallOption) (*DownloadRowsResponse, error)
}

type fibreClient struct {
	cc grpc1.ClientConn
}

func NewFibreClient(cc grpc1.ClientConn) FibreClient {
	return &fibreClient{cc}
}

func (c *fibreClient) UploadRows(ctx context.Context, in *UploadRowsRequest, opts ...grpc.CallOption) (*UploadRowsResponse, error) {
	out := new(UploadRowsResponse)
	err := c.cc.Invoke(ctx, "/celestia.fibre.v1.Fibre/UploadRows", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fibreClient) DownloadRows(ctx context.Context, in *DownloadRowsRequest, opts ...grpc.CallOption) (*DownloadRowsResponse, error) {
	out := new(DownloadRowsResponse)
	err := c.cc.Invoke(ctx, "/celestia.fibre.v1.Fibre/DownloadRows", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FibreServer is the server API for Fibre service.
type FibreServer interface {
	UploadRows(context.Context, *UploadRowsRequest) (*UploadRowsResponse, error)
	DownloadRows(context.Context, *DownloadRowsRequest) (*DownloadRowsResponse, error)
}

// UnimplementedFibreServer can be embedded to have forward compatible implementations.
type UnimplementedFibreServer struct {
}

func (*UnimplementedFibreServer) UploadRows(ctx context.Context, req *UploadRowsRequest) (*UploadRowsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadRows not implemented")
}
func (*UnimplementedFibreServer) DownloadRows(ctx context.Context, req *DownloadRowsRequest) (*DownloadRowsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DownloadRows not implemented")
}

func RegisterFibreServer(s grpc1.Server, srv FibreServer) {
	s.RegisterService(&_Fibre_serviceDesc, srv)
}

func _Fibre_UploadRows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadRowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FibreServer).UploadRows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/celestia.fibre.v1.Fibre/UploadRows",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FibreServer).UploadRows(ctx, req.(*UploadRowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fibre_DownloadRows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadRowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FibreServer).DownloadRows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/celestia.fibre.v1.Fibre/DownloadRows",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FibreServer).DownloadRows(ctx, req.(*DownloadRowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Fibre_serviceDesc = _Fibre_serviceDesc
var _Fibre_serviceDesc = grpc.ServiceDesc{
	ServiceName: "celestia.fibre.v1.Fibre",
	HandlerType: (*FibreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadRows",
			Handler:    _Fibre_UploadRows_Handler,
		},
		{
			MethodName: "DownloadRows",
			Handler:    _Fibre_DownloadRows_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "celestia/fibre/v1/service.proto",
}

func (m *Row) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Row) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Row) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Proof) > 0 {
		for iNdEx := len(m.Proof) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Proof[iNdEx])
			copy(dAtA[i:], m.Proof[iNdEx])
			i = encodeVarintService(dAtA, i, uint64(len(m.Proof[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Data) > 0 {
		i -= len(m.Data)
		copy(dAtA[i:], m.Data)
		i = encodeVarintService(dAtA, i, uint64(len(m.Data)))
		i--
		dAtA[i] = 0x12
	}
	if m.Index != 0 {
		i = encodeVarintService(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Rows) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Rows) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Rows) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Rlc != nil {
		{
			size := m.Rlc.Size()
			i -= size
			if _, err := m.Rlc.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if len(m.Rows) > 0 {
		for iNdEx := len(m.Rows) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Rows[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintService(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *Rows_Coefficients) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Rows_Coefficients) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Coefficients != nil {
		i -= len(m.Coefficients)
		copy(dAtA[i:], m.Coefficients)
		i = encodeVarintService(dAtA, i, uint64(len(m.Coefficients)))
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}
func (m *Rows_Root) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Rows_Root) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Root != nil {
		i -= len(m.Root)
		copy(dAtA[i:], m.Root)
		i = encodeVarintService(dAtA, i, uint64(len(m.Root)))
		i--
		dAtA[i] = 0x1a
	}
	return len(dAtA) - i, nil
}
func (m *UploadRowsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UploadRowsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UploadRowsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Rows != nil {
		{
			size, err := m.Rows.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintService(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Promise != nil {
		{
			size, err := m.Promise.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintService(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *UploadRowsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UploadRowsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UploadRowsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ValidatorSignature) > 0 {
		i -= len(m.ValidatorSignature)
		copy(dAtA[i:], m.ValidatorSignature)
		i = encodeVarintService(dAtA, i, uint64(len(m.ValidatorSignature)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DownloadRowsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DownloadRowsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DownloadRowsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Commitment) > 0 {
		i -= len(m.Commitment)
		copy(dAtA[i:], m.Commitment)
		i = encodeVarintService(dAtA, i, uint64(len(m.Commitment)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DownloadRowsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DownloadRowsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DownloadRowsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Rows != nil {
		{
			size, err := m.Rows.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintService(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintService(dAtA []byte, offset int, v uint64) int {
	offset -= sovService(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Row) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Index != 0 {
		n += 1 + sovService(uint64(m.Index))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovService(uint64(l))
	}
	if len(m.Proof) > 0 {
		for _, b := range m.Proof {
			l = len(b)
			n += 1 + l + sovService(uint64(l))
		}
	}
	return n
}

func (m *Rows) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Rows) > 0 {
		for _, e := range m.Rows {
			l = e.Size()
			n += 1 + l + sovService(uint64(l))
		}
	}
	if m.Rlc != nil {
		n += m.Rlc.Size()
	}
	return n
}

func (m *Rows_Coefficients) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Coefficients != nil {
		l = len(m.Coefficients)
		n += 1 + l + sovService(uint64(l))
	}
	return n
}
func (m *Rows_Root) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Root != nil {
		l = len(m.Root)
		n += 1 + l + sovService(uint64(l))
	}
	return n
}
func (m *UploadRowsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Promise != nil {
		l = m.Promise.Size()
		n += 1 + l + sovService(uint64(l))
	}
	if m.Rows != nil {
		l = m.Rows.Size()
		n += 1 + l + sovService(uint64(l))
	}
	return n
}

func (m *UploadRowsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ValidatorSignature)
	if l > 0 {
		n += 1 + l + sovService(uint64(l))
	}
	return n
}

func (m *DownloadRowsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Commitment)
	if l > 0 {
		n += 1 + l + sovService(uint64(l))
	}
	return n
}

func (m *DownloadRowsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Rows != nil {
		l = m.Rows.Size()
		n += 1 + l + sovService(uint64(l))
	}
	return n
}

func sovService(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozService(x uint64) (n int) {
	return sovService(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Row) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Row: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Row: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proof", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proof = append(m.Proof, make([]byte, postIndex-iNdEx))
			copy(m.Proof[len(m.Proof)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Rows) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Rows: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Rows: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rows", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Rows = append(m.Rows, &Row{})
			if err := m.Rows[len(m.Rows)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Coefficients", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := make([]byte, postIndex-iNdEx)
			copy(v, dAtA[iNdEx:postIndex])
			m.Rlc = &Rows_Coefficients{v}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Root", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := make([]byte, postIndex-iNdEx)
			copy(v, dAtA[iNdEx:postIndex])
			m.Rlc = &Rows_Root{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UploadRowsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UploadRowsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UploadRowsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Promise", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Promise == nil {
				m.Promise = &PaymentPromise{}
			}
			if err := m.Promise.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rows", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Rows == nil {
				m.Rows = &Rows{}
			}
			if err := m.Rows.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UploadRowsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UploadRowsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UploadRowsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorSignature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorSignature = append(m.ValidatorSignature[:0], dAtA[iNdEx:postIndex]...)
			if m.ValidatorSignature == nil {
				m.ValidatorSignature = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DownloadRowsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DownloadRowsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DownloadRowsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Commitment", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Commitment = append(m.Commitment[:0], dAtA[iNdEx:postIndex]...)
			if m.Commitment == nil {
				m.Commitment = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DownloadRowsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DownloadRowsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DownloadRowsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rows", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Rows == nil {
				m.Rows = &Rows{}
			}
			if err := m.Rows.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipService(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowService
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowService
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowService
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthService
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupService
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthService
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthService        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowService          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupService = fmt.Errorf("proto: unexpected end of group")
)
