// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: fibre.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Fibre_UploadRows_FullMethodName = "/fibre.service.v1.Fibre/UploadRows"
	Fibre_GetRows_FullMethodName    = "/fibre.service.v1.Fibre/GetRows"
)

// FibreClient is the client API for Fibre service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FibreClient interface {
	UploadRows(ctx context.Context, in *UploadRowsRequest, opts ...grpc.CallOption) (*UploadRowsResponse, error)
	GetRows(ctx context.Context, in *GetRowsRequest, opts ...grpc.CallOption) (*GetRowsResponse, error)
}

type fibreClient struct {
	cc grpc.ClientConnInterface
}

func NewFibreClient(cc grpc.ClientConnInterface) FibreClient {
	return &fibreClient{cc}
}

func (c *fibreClient) UploadRows(ctx context.Context, in *UploadRowsRequest, opts ...grpc.CallOption) (*UploadRowsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadRowsResponse)
	err := c.cc.Invoke(ctx, Fibre_UploadRows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fibreClient) GetRows(ctx context.Context, in *GetRowsRequest, opts ...grpc.CallOption) (*GetRowsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRowsResponse)
	err := c.cc.Invoke(ctx, Fibre_GetRows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FibreServer is the server API for Fibre service.
// All implementations must embed UnimplementedFibreServer
// for forward compatibility.
type FibreServer interface {
	UploadRows(context.Context, *UploadRowsRequest) (*UploadRowsResponse, error)
	GetRows(context.Context, *GetRowsRequest) (*GetRowsResponse, error)
	mustEmbedUnimplementedFibreServer()
}

// UnimplementedFibreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFibreServer struct{}

func (UnimplementedFibreServer) UploadRows(context.Context, *UploadRowsRequest) (*UploadRowsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadRows not implemented")
}
func (UnimplementedFibreServer) GetRows(context.Context, *GetRowsRequest) (*GetRowsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRows not implemented")
}
func (UnimplementedFibreServer) mustEmbedUnimplementedFibreServer() {}
func (UnimplementedFibreServer) testEmbeddedByValue()               {}

// UnsafeFibreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FibreServer will
// result in compilation errors.
type UnsafeFibreServer interface {
	mustEmbedUnimplementedFibreServer()
}

func RegisterFibreServer(s grpc.ServiceRegistrar, srv FibreServer) {
	// If the following call pancis, it indicates UnimplementedFibreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Fibre_ServiceDesc, srv)
}

func _Fibre_UploadRows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadRowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FibreServer).UploadRows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fibre_UploadRows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FibreServer).UploadRows(ctx, req.(*UploadRowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fibre_GetRows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FibreServer).GetRows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fibre_GetRows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FibreServer).GetRows(ctx, req.(*GetRowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Fibre_ServiceDesc is the grpc.ServiceDesc for Fibre service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Fibre_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fibre.service.v1.Fibre",
	HandlerType: (*FibreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadRows",
			Handler:    _Fibre_UploadRows_Handler,
		},
		{
			MethodName: "GetRows",
			Handler:    _Fibre_GetRows_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fibre.proto",
}
