// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: fibre.proto

package proto

import (
	types "github.com/celestiaorg/celestia-app/v6/x/fibre/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Proof         [][]byte               `protobuf:"bytes,3,rep,name=proof,proto3" json:"proof,omitempty"`
	RlcRoot       []byte                 `protobuf:"bytes,4,opt,name=rlc_root,json=rlcRoot,proto3,oneof" json:"rlc_root,omitempty"` // len == 32 when present
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_fibre_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_fibre_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_fibre_proto_rawDescGZIP(), []int{0}
}

func (x *Row) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Row) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Row) GetProof() [][]byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *Row) GetRlcRoot() []byte {
	if x != nil {
		return x.RlcRoot
	}
	return nil
}

type RlcOrig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coeffs        []*RlcOrig_GF128       `protobuf:"bytes,1,rep,name=coeffs,proto3" json:"coeffs,omitempty"` // len == K
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RlcOrig) Reset() {
	*x = RlcOrig{}
	mi := &file_fibre_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RlcOrig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RlcOrig) ProtoMessage() {}

func (x *RlcOrig) ProtoReflect() protoreflect.Message {
	mi := &file_fibre_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RlcOrig.ProtoReflect.Descriptor instead.
func (*RlcOrig) Descriptor() ([]byte, []int) {
	return file_fibre_proto_rawDescGZIP(), []int{1}
}

func (x *RlcOrig) GetCoeffs() []*RlcOrig_GF128 {
	if x != nil {
		return x.Coeffs
	}
	return nil
}

type UploadRowsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Promise       *types.PaymentPromise  `protobuf:"bytes,1,opt,name=promise,proto3" json:"promise,omitempty"`
	Rows          []*Row                 `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	RlcOrig       *RlcOrig               `protobuf:"bytes,3,opt,name=rlc_orig,json=rlcOrig,proto3" json:"rlc_orig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRowsRequest) Reset() {
	*x = UploadRowsRequest{}
	mi := &file_fibre_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRowsRequest) ProtoMessage() {}

func (x *UploadRowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fibre_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRowsRequest.ProtoReflect.Descriptor instead.
func (*UploadRowsRequest) Descriptor() ([]byte, []int) {
	return file_fibre_proto_rawDescGZIP(), []int{2}
}

func (x *UploadRowsRequest) GetPromise() *types.PaymentPromise {
	if x != nil {
		return x.Promise
	}
	return nil
}

func (x *UploadRowsRequest) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *UploadRowsRequest) GetRlcOrig() *RlcOrig {
	if x != nil {
		return x.RlcOrig
	}
	return nil
}

type UploadRowsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ValidatorSignature []byte                 `protobuf:"bytes,1,opt,name=validator_signature,json=validatorSignature,proto3" json:"validator_signature,omitempty"` // SPECDO: secp256k1 over SignBytes
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UploadRowsResponse) Reset() {
	*x = UploadRowsResponse{}
	mi := &file_fibre_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRowsResponse) ProtoMessage() {}

func (x *UploadRowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fibre_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRowsResponse.ProtoReflect.Descriptor instead.
func (*UploadRowsResponse) Descriptor() ([]byte, []int) {
	return file_fibre_proto_rawDescGZIP(), []int{3}
}

func (x *UploadRowsResponse) GetValidatorSignature() []byte {
	if x != nil {
		return x.ValidatorSignature
	}
	return nil
}

type GetRowsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commitment    []byte                 `protobuf:"bytes,1,opt,name=commitment,proto3" json:"commitment,omitempty"` // len == 32
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRowsRequest) Reset() {
	*x = GetRowsRequest{}
	mi := &file_fibre_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRowsRequest) ProtoMessage() {}

func (x *GetRowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fibre_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRowsRequest.ProtoReflect.Descriptor instead.
func (*GetRowsRequest) Descriptor() ([]byte, []int) {
	return file_fibre_proto_rawDescGZIP(), []int{4}
}

func (x *GetRowsRequest) GetCommitment() []byte {
	if x != nil {
		return x.Commitment
	}
	return nil
}

type GetRowsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*Row                 `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRowsResponse) Reset() {
	*x = GetRowsResponse{}
	mi := &file_fibre_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRowsResponse) ProtoMessage() {}

func (x *GetRowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fibre_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRowsResponse.ProtoReflect.Descriptor instead.
func (*GetRowsResponse) Descriptor() ([]byte, []int) {
	return file_fibre_proto_rawDescGZIP(), []int{5}
}

func (x *GetRowsResponse) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

type RlcOrig_GF128 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coeffs        []byte                 `protobuf:"bytes,1,opt,name=coeffs,proto3" json:"coeffs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RlcOrig_GF128) Reset() {
	*x = RlcOrig_GF128{}
	mi := &file_fibre_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RlcOrig_GF128) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RlcOrig_GF128) ProtoMessage() {}

func (x *RlcOrig_GF128) ProtoReflect() protoreflect.Message {
	mi := &file_fibre_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RlcOrig_GF128.ProtoReflect.Descriptor instead.
func (*RlcOrig_GF128) Descriptor() ([]byte, []int) {
	return file_fibre_proto_rawDescGZIP(), []int{1, 0}
}

func (x *RlcOrig_GF128) GetCoeffs() []byte {
	if x != nil {
		return x.Coeffs
	}
	return nil
}

var File_fibre_proto protoreflect.FileDescriptor

const file_fibre_proto_rawDesc = "" +
	"\n" +
	"\vfibre.proto\x12\x10fibre.service.v1\x1a\x1dcelestia/fibre/v1/fibre.proto\"r\n" +
	"\x03Row\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x14\n" +
	"\x05proof\x18\x03 \x03(\fR\x05proof\x12\x1e\n" +
	"\brlc_root\x18\x04 \x01(\fH\x00R\arlcRoot\x88\x01\x01B\v\n" +
	"\t_rlc_root\"c\n" +
	"\aRlcOrig\x127\n" +
	"\x06coeffs\x18\x01 \x03(\v2\x1f.fibre.service.v1.RlcOrig.GF128R\x06coeffs\x1a\x1f\n" +
	"\x05GF128\x12\x16\n" +
	"\x06coeffs\x18\x01 \x01(\fR\x06coeffs\"\xb1\x01\n" +
	"\x11UploadRowsRequest\x12;\n" +
	"\apromise\x18\x01 \x01(\v2!.celestia.fibre.v1.PaymentPromiseR\apromise\x12)\n" +
	"\x04rows\x18\x02 \x03(\v2\x15.fibre.service.v1.RowR\x04rows\x124\n" +
	"\brlc_orig\x18\x03 \x01(\v2\x19.fibre.service.v1.RlcOrigR\arlcOrig\"E\n" +
	"\x12UploadRowsResponse\x12/\n" +
	"\x13validator_signature\x18\x01 \x01(\fR\x12validatorSignature\"0\n" +
	"\x0eGetRowsRequest\x12\x1e\n" +
	"\n" +
	"commitment\x18\x01 \x01(\fR\n" +
	"commitment\"<\n" +
	"\x0fGetRowsResponse\x12)\n" +
	"\x04rows\x18\x01 \x03(\v2\x15.fibre.service.v1.RowR\x04rows2\xb0\x01\n" +
	"\x05Fibre\x12W\n" +
	"\n" +
	"UploadRows\x12#.fibre.service.v1.UploadRowsRequest\x1a$.fibre.service.v1.UploadRowsResponse\x12N\n" +
	"\aGetRows\x12 .fibre.service.v1.GetRowsRequest\x1a!.fibre.service.v1.GetRowsResponseB6Z4github.com/celestiaorg/celestia-app/v6/x/fibre/protob\x06proto3"

var (
	file_fibre_proto_rawDescOnce sync.Once
	file_fibre_proto_rawDescData []byte
)

func file_fibre_proto_rawDescGZIP() []byte {
	file_fibre_proto_rawDescOnce.Do(func() {
		file_fibre_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fibre_proto_rawDesc), len(file_fibre_proto_rawDesc)))
	})
	return file_fibre_proto_rawDescData
}

var file_fibre_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_fibre_proto_goTypes = []any{
	(*Row)(nil),                  // 0: fibre.service.v1.Row
	(*RlcOrig)(nil),              // 1: fibre.service.v1.RlcOrig
	(*UploadRowsRequest)(nil),    // 2: fibre.service.v1.UploadRowsRequest
	(*UploadRowsResponse)(nil),   // 3: fibre.service.v1.UploadRowsResponse
	(*GetRowsRequest)(nil),       // 4: fibre.service.v1.GetRowsRequest
	(*GetRowsResponse)(nil),      // 5: fibre.service.v1.GetRowsResponse
	(*RlcOrig_GF128)(nil),        // 6: fibre.service.v1.RlcOrig.GF128
	(*types.PaymentPromise)(nil), // 7: celestia.fibre.v1.PaymentPromise
}
var file_fibre_proto_depIdxs = []int32{
	6, // 0: fibre.service.v1.RlcOrig.coeffs:type_name -> fibre.service.v1.RlcOrig.GF128
	7, // 1: fibre.service.v1.UploadRowsRequest.promise:type_name -> celestia.fibre.v1.PaymentPromise
	0, // 2: fibre.service.v1.UploadRowsRequest.rows:type_name -> fibre.service.v1.Row
	1, // 3: fibre.service.v1.UploadRowsRequest.rlc_orig:type_name -> fibre.service.v1.RlcOrig
	0, // 4: fibre.service.v1.GetRowsResponse.rows:type_name -> fibre.service.v1.Row
	2, // 5: fibre.service.v1.Fibre.UploadRows:input_type -> fibre.service.v1.UploadRowsRequest
	4, // 6: fibre.service.v1.Fibre.GetRows:input_type -> fibre.service.v1.GetRowsRequest
	3, // 7: fibre.service.v1.Fibre.UploadRows:output_type -> fibre.service.v1.UploadRowsResponse
	5, // 8: fibre.service.v1.Fibre.GetRows:output_type -> fibre.service.v1.GetRowsResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_fibre_proto_init() }
func file_fibre_proto_init() {
	if File_fibre_proto != nil {
		return
	}
	file_fibre_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fibre_proto_rawDesc), len(file_fibre_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fibre_proto_goTypes,
		DependencyIndexes: file_fibre_proto_depIdxs,
		MessageInfos:      file_fibre_proto_msgTypes,
	}.Build()
	File_fibre_proto = out.File
	file_fibre_proto_goTypes = nil
	file_fibre_proto_depIdxs = nil
}
