syntax = "proto3";
package celestia.fibre.v1;

option go_package = "github.com/celestiaorg/celestia-app/x/fibre/types";

import "celestia/fibre/v1/fibre.proto";

message Row {
  uint32 index = 1;
  bytes data = 2;
  repeated bytes proof = 3;
}

message Rows {
  repeated Row rows = 1;
  oneof rlc {
    bytes coefficients = 2; // serialized rlc coefficients, 16 bytes per original row
    bytes root = 3; // const len == 32 when present
  }
}

message UploadRowsRequest {
  celestia.fibre.v1.PaymentPromise promise = 1;
  Rows rows = 2; // with rlc coefficients
}

message UploadRowsResponse {
  bytes validator_signature = 1; // const len == 32
}

message DownloadRowsRequest {
  bytes commitment = 1; // const len == 32
}

message DownloadRowsResponse {
  Rows rows = 1; // with rlc root
}

service Fibre {
  rpc UploadRows(UploadRowsRequest) returns (UploadRowsResponse);
  rpc DownloadRows(DownloadRowsRequest) returns (DownloadRowsResponse);
}
