syntax = "proto3";
package celestia.fibre.v1;

option go_package = "github.com/celestiaorg/celestia-app/x/fibre/types";

import "celestia/fibre/v1/fibre.proto";

// Row represents a row of data in a Fibre blob.
message Row {
  uint32 index = 1;
  bytes data = 2;
  repeated bytes proof = 3;
}

// Rows represents a collection of rows in a Fibre blob.
// With two ways of proving data correctness:
// 1. Using RLC coefficients when there is not enough rows to reconstruct the data blob. (Upload case)
// 2. Using a Merkle root of RLC tree, when there is sufficient rows to reconstruct the data blob. (Download case)
message Rows {
  repeated Row rows = 1;
  oneof rlc {
    bytes coefficients = 2; // serialized rlc coefficients, 16 bytes per original row
    bytes root = 3; // const len == 32 when present
  }
}

// UploadRowsRequest is the request message for the UploadRows RPC method.
message UploadRowsRequest {
  celestia.fibre.v1.PaymentPromise promise = 1;
  Rows rows = 2; // with rlc coefficients
}

// UploadRowsResponse is the response message for the UploadRows RPC method.
message UploadRowsResponse {
  bytes validator_signature = 1; // const len == 32
}

// DownloadRowsRequest is the request message for the DownloadRows RPC method.
message DownloadRowsRequest {
  bytes commitment = 1; // const len == 32
}

// DownloadRowsResponse is the response message for the DownloadRows RPC method.
message DownloadRowsResponse {
  Rows rows = 1; // with rlc root
}

service Fibre {
  rpc UploadRows(UploadRowsRequest) returns (UploadRowsResponse);
  rpc DownloadRows(DownloadRowsRequest) returns (DownloadRowsResponse);
}
