// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: celestia/valaddr/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryFibreProviderInfoRequest is the request type for the Query/FibreProviderInfo RPC method.
type QueryFibreProviderInfoRequest struct {
	// validator_consensus_address is the validator consensus address (celestiavalcons...)
	ValidatorConsensusAddress string `protobuf:"bytes,1,opt,name=validator_consensus_address,json=validatorConsensusAddress,proto3" json:"validator_consensus_address,omitempty"`
}

func (m *QueryFibreProviderInfoRequest) Reset()         { *m = QueryFibreProviderInfoRequest{} }
func (m *QueryFibreProviderInfoRequest) String() string { return proto.CompactTextString(m) }
func (*QueryFibreProviderInfoRequest) ProtoMessage()    {}
func (*QueryFibreProviderInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e66720a0aa696609, []int{0}
}
func (m *QueryFibreProviderInfoRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryFibreProviderInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryFibreProviderInfoRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryFibreProviderInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryFibreProviderInfoRequest.Merge(m, src)
}
func (m *QueryFibreProviderInfoRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryFibreProviderInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryFibreProviderInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryFibreProviderInfoRequest proto.InternalMessageInfo

func (m *QueryFibreProviderInfoRequest) GetValidatorConsensusAddress() string {
	if m != nil {
		return m.ValidatorConsensusAddress
	}
	return ""
}

// QueryFibreProviderInfoResponse is the response type for the Query/FibreProviderInfo RPC method.
type QueryFibreProviderInfoResponse struct {
	// info contains the fibre provider information
	Info *FibreProviderInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	// found indicates if the validator has registered info
	Found bool `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
}

func (m *QueryFibreProviderInfoResponse) Reset()         { *m = QueryFibreProviderInfoResponse{} }
func (m *QueryFibreProviderInfoResponse) String() string { return proto.CompactTextString(m) }
func (*QueryFibreProviderInfoResponse) ProtoMessage()    {}
func (*QueryFibreProviderInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e66720a0aa696609, []int{1}
}
func (m *QueryFibreProviderInfoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryFibreProviderInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryFibreProviderInfoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryFibreProviderInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryFibreProviderInfoResponse.Merge(m, src)
}
func (m *QueryFibreProviderInfoResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryFibreProviderInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryFibreProviderInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryFibreProviderInfoResponse proto.InternalMessageInfo

func (m *QueryFibreProviderInfoResponse) GetInfo() *FibreProviderInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *QueryFibreProviderInfoResponse) GetFound() bool {
	if m != nil {
		return m.Found
	}
	return false
}

// QueryAllFibreProvidersRequest is the request type for the Query/AllFibreProviders RPC method.
type QueryAllFibreProvidersRequest struct {
}

func (m *QueryAllFibreProvidersRequest) Reset()         { *m = QueryAllFibreProvidersRequest{} }
func (m *QueryAllFibreProvidersRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllFibreProvidersRequest) ProtoMessage()    {}
func (*QueryAllFibreProvidersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e66720a0aa696609, []int{2}
}
func (m *QueryAllFibreProvidersRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllFibreProvidersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllFibreProvidersRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllFibreProvidersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllFibreProvidersRequest.Merge(m, src)
}
func (m *QueryAllFibreProvidersRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllFibreProvidersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllFibreProvidersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllFibreProvidersRequest proto.InternalMessageInfo

// QueryAllFibreProvidersResponse is the response type for the Query/AllFibreProviders RPC method.
type QueryAllFibreProvidersResponse struct {
	// providers contains all fibre providers with a host defined
	Providers []FibreProvider `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers"`
}

func (m *QueryAllFibreProvidersResponse) Reset()         { *m = QueryAllFibreProvidersResponse{} }
func (m *QueryAllFibreProvidersResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllFibreProvidersResponse) ProtoMessage()    {}
func (*QueryAllFibreProvidersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e66720a0aa696609, []int{3}
}
func (m *QueryAllFibreProvidersResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllFibreProvidersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllFibreProvidersResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllFibreProvidersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllFibreProvidersResponse.Merge(m, src)
}
func (m *QueryAllFibreProvidersResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllFibreProvidersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllFibreProvidersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllFibreProvidersResponse proto.InternalMessageInfo

func (m *QueryAllFibreProvidersResponse) GetProviders() []FibreProvider {
	if m != nil {
		return m.Providers
	}
	return nil
}

// FibreProvider represents a validator and their fibre provider information.
type FibreProvider struct {
	// validator_consensus_address is the validator consensus address (celestiavalcons...)
	ValidatorConsensusAddress string `protobuf:"bytes,1,opt,name=validator_consensus_address,json=validatorConsensusAddress,proto3" json:"validator_consensus_address,omitempty"`
	// info contains the fibre provider information
	Info FibreProviderInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info"`
}

func (m *FibreProvider) Reset()         { *m = FibreProvider{} }
func (m *FibreProvider) String() string { return proto.CompactTextString(m) }
func (*FibreProvider) ProtoMessage()    {}
func (*FibreProvider) Descriptor() ([]byte, []int) {
	return fileDescriptor_e66720a0aa696609, []int{4}
}
func (m *FibreProvider) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FibreProvider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FibreProvider.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FibreProvider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FibreProvider.Merge(m, src)
}
func (m *FibreProvider) XXX_Size() int {
	return m.Size()
}
func (m *FibreProvider) XXX_DiscardUnknown() {
	xxx_messageInfo_FibreProvider.DiscardUnknown(m)
}

var xxx_messageInfo_FibreProvider proto.InternalMessageInfo

func (m *FibreProvider) GetValidatorConsensusAddress() string {
	if m != nil {
		return m.ValidatorConsensusAddress
	}
	return ""
}

func (m *FibreProvider) GetInfo() FibreProviderInfo {
	if m != nil {
		return m.Info
	}
	return FibreProviderInfo{}
}

// FibreProviderInfo contains the service details for a fibre provider.
type FibreProviderInfo struct {
	// host is the network address for the fibre service provider
	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
}

func (m *FibreProviderInfo) Reset()         { *m = FibreProviderInfo{} }
func (m *FibreProviderInfo) String() string { return proto.CompactTextString(m) }
func (*FibreProviderInfo) ProtoMessage()    {}
func (*FibreProviderInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e66720a0aa696609, []int{5}
}
func (m *FibreProviderInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FibreProviderInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FibreProviderInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FibreProviderInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FibreProviderInfo.Merge(m, src)
}
func (m *FibreProviderInfo) XXX_Size() int {
	return m.Size()
}
func (m *FibreProviderInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FibreProviderInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FibreProviderInfo proto.InternalMessageInfo

func (m *FibreProviderInfo) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryFibreProviderInfoRequest)(nil), "celestia.valaddr.v1.QueryFibreProviderInfoRequest")
	proto.RegisterType((*QueryFibreProviderInfoResponse)(nil), "celestia.valaddr.v1.QueryFibreProviderInfoResponse")
	proto.RegisterType((*QueryAllFibreProvidersRequest)(nil), "celestia.valaddr.v1.QueryAllFibreProvidersRequest")
	proto.RegisterType((*QueryAllFibreProvidersResponse)(nil), "celestia.valaddr.v1.QueryAllFibreProvidersResponse")
	proto.RegisterType((*FibreProvider)(nil), "celestia.valaddr.v1.FibreProvider")
	proto.RegisterType((*FibreProviderInfo)(nil), "celestia.valaddr.v1.FibreProviderInfo")
}

func init() { proto.RegisterFile("celestia/valaddr/v1/query.proto", fileDescriptor_e66720a0aa696609) }

var fileDescriptor_e66720a0aa696609 = []byte{
	// 472 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0x3f, 0x6f, 0x13, 0x31,
	0x18, 0xc6, 0xe3, 0x90, 0x22, 0xea, 0x8a, 0xa1, 0xa6, 0x43, 0x08, 0x70, 0x09, 0x1e, 0x68, 0x96,
	0x9c, 0xd5, 0x74, 0x02, 0x89, 0x3f, 0x2d, 0xa2, 0x12, 0x1b, 0x84, 0x8d, 0x25, 0x72, 0x72, 0xce,
	0xe5, 0xa4, 0xc3, 0xef, 0xd5, 0xf6, 0x9d, 0xa8, 0x10, 0x0b, 0x9f, 0x00, 0xc4, 0x67, 0xe0, 0x93,
	0xb0, 0x74, 0xac, 0xc4, 0xc2, 0x84, 0x50, 0xc2, 0x57, 0x60, 0x47, 0xe7, 0xf3, 0x85, 0x46, 0xf9,
	0x83, 0x22, 0x36, 0xdf, 0xf9, 0xf7, 0xf8, 0x7d, 0x9f, 0xc7, 0xaf, 0x71, 0x73, 0x28, 0x62, 0xa1,
	0x4d, 0xc4, 0x59, 0xc6, 0x63, 0x1e, 0x04, 0x8a, 0x65, 0x07, 0xec, 0x34, 0x15, 0xea, 0xcc, 0x4f,
	0x14, 0x18, 0x20, 0x37, 0x4a, 0xc0, 0x77, 0x80, 0x9f, 0x1d, 0x34, 0xf6, 0x42, 0x08, 0xc1, 0xee,
	0xb3, 0x7c, 0x55, 0xa0, 0x8d, 0xdb, 0x21, 0x40, 0x18, 0x0b, 0xc6, 0x93, 0x88, 0x71, 0x29, 0xc1,
	0x70, 0x13, 0x81, 0xd4, 0xc5, 0x2e, 0xed, 0xe3, 0x3b, 0x2f, 0xf3, 0x73, 0x4f, 0xa2, 0x81, 0x12,
	0x2f, 0x14, 0x64, 0x51, 0x20, 0xd4, 0x73, 0x39, 0x82, 0x9e, 0x38, 0x4d, 0x85, 0x36, 0xe4, 0x11,
	0xbe, 0x95, 0xf1, 0x38, 0x0a, 0xb8, 0x01, 0xd5, 0x1f, 0x82, 0xd4, 0x42, 0xea, 0x54, 0xf7, 0xf3,
	0x9a, 0x42, 0xeb, 0x3a, 0x6a, 0xa1, 0xf6, 0x76, 0xef, 0xe6, 0x0c, 0x79, 0x5a, 0x12, 0x47, 0x05,
	0x40, 0x15, 0xf6, 0x56, 0x15, 0xd0, 0x49, 0x0e, 0x93, 0x07, 0xb8, 0x16, 0xc9, 0x11, 0xd8, 0xa3,
	0x76, 0xba, 0xf7, 0xfc, 0x25, 0xd6, 0xfc, 0x45, 0xb5, 0xd5, 0x90, 0x3d, 0xbc, 0x35, 0x82, 0x54,
	0x06, 0xf5, 0x6a, 0x0b, 0xb5, 0xaf, 0xf5, 0x8a, 0x0f, 0xda, 0x74, 0xa6, 0x8e, 0xe2, 0x78, 0x4e,
	0xa8, 0x9d, 0x29, 0x3a, 0x76, 0x4d, 0x2d, 0x01, 0x5c, 0x53, 0x27, 0x78, 0x3b, 0x29, 0x7f, 0xd6,
	0x51, 0xeb, 0x4a, 0x7b, 0xa7, 0x4b, 0xff, 0xdd, 0xd9, 0x71, 0xed, 0xfc, 0x47, 0xb3, 0xd2, 0xfb,
	0x2b, 0xa5, 0x9f, 0x10, 0xbe, 0x3e, 0x87, 0xfc, 0x6f, 0xa0, 0xe4, 0x89, 0x8b, 0xab, 0xba, 0x49,
	0x5c, 0xae, 0x31, 0xab, 0xa4, 0xfb, 0x78, 0x77, 0x01, 0x20, 0x04, 0xd7, 0xc6, 0xa0, 0x8d, 0xab,
	0x6f, 0xd7, 0xdd, 0xdf, 0x55, 0xbc, 0x65, 0x73, 0x22, 0x5f, 0xd1, 0x32, 0x4d, 0x77, 0x69, 0xf1,
	0xb5, 0xf3, 0xd4, 0x38, 0xdc, 0x48, 0x53, 0xdc, 0x06, 0x7d, 0xf6, 0xe1, 0xdb, 0xaf, 0xcf, 0xd5,
	0xc7, 0xe4, 0xe1, 0xe5, 0xf7, 0x30, 0xca, 0xf1, 0x4e, 0x19, 0x75, 0x27, 0xb7, 0xc6, 0xde, 0xad,
	0x89, 0xf6, 0x3d, 0xf9, 0x82, 0xf0, 0xee, 0xc2, 0x95, 0xaf, 0x73, 0xb1, 0x6a, 0x80, 0xd6, 0xb9,
	0x58, 0x39, 0x53, 0x74, 0xdf, 0xba, 0xb8, 0x4b, 0x9a, 0x97, 0x5d, 0xf0, 0x38, 0xee, 0xcc, 0x3b,
	0xd1, 0xc7, 0xaf, 0xce, 0x27, 0x1e, 0xba, 0x98, 0x78, 0xe8, 0xe7, 0xc4, 0x43, 0x1f, 0xa7, 0x5e,
	0xe5, 0x62, 0xea, 0x55, 0xbe, 0x4f, 0xbd, 0xca, 0xeb, 0xfb, 0x61, 0x64, 0xc6, 0xe9, 0xc0, 0x1f,
	0xc2, 0x1b, 0x56, 0x76, 0x00, 0x2a, 0x9c, 0xad, 0x3b, 0x3c, 0x49, 0x8a, 0xe3, 0xd8, 0xdb, 0x59,
	0x15, 0x73, 0x96, 0x08, 0x3d, 0xb8, 0x6a, 0x1f, 0xfc, 0xe1, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x72, 0x68, 0x55, 0x7d, 0x5c, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// FibreProviderInfo queries the fibre provider information for a specific validator
	FibreProviderInfo(ctx context.Context, in *QueryFibreProviderInfoRequest, opts ...grpc.CallOption) (*QueryFibreProviderInfoResponse, error)
	// AllFibreProviders queries fibre provider information for all validators
	AllFibreProviders(ctx context.Context, in *QueryAllFibreProvidersRequest, opts ...grpc.CallOption) (*QueryAllFibreProvidersResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) FibreProviderInfo(ctx context.Context, in *QueryFibreProviderInfoRequest, opts ...grpc.CallOption) (*QueryFibreProviderInfoResponse, error) {
	out := new(QueryFibreProviderInfoResponse)
	err := c.cc.Invoke(ctx, "/celestia.valaddr.v1.Query/FibreProviderInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllFibreProviders(ctx context.Context, in *QueryAllFibreProvidersRequest, opts ...grpc.CallOption) (*QueryAllFibreProvidersResponse, error) {
	out := new(QueryAllFibreProvidersResponse)
	err := c.cc.Invoke(ctx, "/celestia.valaddr.v1.Query/AllFibreProviders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// FibreProviderInfo queries the fibre provider information for a specific validator
	FibreProviderInfo(context.Context, *QueryFibreProviderInfoRequest) (*QueryFibreProviderInfoResponse, error)
	// AllFibreProviders queries fibre provider information for all validators
	AllFibreProviders(context.Context, *QueryAllFibreProvidersRequest) (*QueryAllFibreProvidersResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) FibreProviderInfo(ctx context.Context, req *QueryFibreProviderInfoRequest) (*QueryFibreProviderInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FibreProviderInfo not implemented")
}
func (*UnimplementedQueryServer) AllFibreProviders(ctx context.Context, req *QueryAllFibreProvidersRequest) (*QueryAllFibreProvidersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllFibreProviders not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_FibreProviderInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFibreProviderInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).FibreProviderInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/celestia.valaddr.v1.Query/FibreProviderInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).FibreProviderInfo(ctx, req.(*QueryFibreProviderInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllFibreProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllFibreProvidersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllFibreProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/celestia.valaddr.v1.Query/AllFibreProviders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllFibreProviders(ctx, req.(*QueryAllFibreProvidersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "celestia.valaddr.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FibreProviderInfo",
			Handler:    _Query_FibreProviderInfo_Handler,
		},
		{
			MethodName: "AllFibreProviders",
			Handler:    _Query_AllFibreProviders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "celestia/valaddr/v1/query.proto",
}

func (m *QueryFibreProviderInfoRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryFibreProviderInfoRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryFibreProviderInfoRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ValidatorConsensusAddress) > 0 {
		i -= len(m.ValidatorConsensusAddress)
		copy(dAtA[i:], m.ValidatorConsensusAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ValidatorConsensusAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryFibreProviderInfoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryFibreProviderInfoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryFibreProviderInfoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Found {
		i--
		if m.Found {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if m.Info != nil {
		{
			size, err := m.Info.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllFibreProvidersRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllFibreProvidersRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllFibreProvidersRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryAllFibreProvidersResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllFibreProvidersResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllFibreProvidersResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Providers) > 0 {
		for iNdEx := len(m.Providers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Providers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *FibreProvider) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FibreProvider) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FibreProvider) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Info.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.ValidatorConsensusAddress) > 0 {
		i -= len(m.ValidatorConsensusAddress)
		copy(dAtA[i:], m.ValidatorConsensusAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ValidatorConsensusAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *FibreProviderInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FibreProviderInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FibreProviderInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Host) > 0 {
		i -= len(m.Host)
		copy(dAtA[i:], m.Host)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Host)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryFibreProviderInfoRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ValidatorConsensusAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryFibreProviderInfoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Info != nil {
		l = m.Info.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Found {
		n += 2
	}
	return n
}

func (m *QueryAllFibreProvidersRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryAllFibreProvidersResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Providers) > 0 {
		for _, e := range m.Providers {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *FibreProvider) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ValidatorConsensusAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = m.Info.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *FibreProviderInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Host)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryFibreProviderInfoRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryFibreProviderInfoRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryFibreProviderInfoRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorConsensusAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorConsensusAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryFibreProviderInfoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryFibreProviderInfoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryFibreProviderInfoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Info", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Info == nil {
				m.Info = &FibreProviderInfo{}
			}
			if err := m.Info.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Found", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Found = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllFibreProvidersRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllFibreProvidersRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllFibreProvidersRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllFibreProvidersResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllFibreProvidersResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllFibreProvidersResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Providers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Providers = append(m.Providers, FibreProvider{})
			if err := m.Providers[len(m.Providers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FibreProvider) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FibreProvider: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FibreProvider: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorConsensusAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorConsensusAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Info", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Info.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FibreProviderInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FibreProviderInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FibreProviderInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Host", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Host = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
