name: build
on:
  workflow_call:
    secrets:
      GH_PRIVATE_MODULES_TOKEN:
        required: true

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1

      - name: Configure Git for private modules
        run: git config --global url."https://${{ secrets.GH_PRIVATE_MODULES_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 #v6.0.0
        with:
          go-version-file: "go.mod"
        env:
          GOPRIVATE: github.com/celestiaorg/*
          GONOSUMDB: github.com/celestiaorg/*

      - name: build
        run: make build
        env:
          GOPRIVATE: github.com/celestiaorg/*
          GONOSUMDB: github.com/celestiaorg/*
