name: build
on:
  workflow_call:
    secrets:
      GH_PRIVATE_MODULES_TOKEN:
        required: true

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0

      - name: Configure Git for private modules
        run: git config --global url."https://${{ secrets.GH_PRIVATE_MODULES_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 #v6.2.0
        with:
          go-version-file: "go.mod"
        env:
          GOPRIVATE: github.com/celestiaorg/*
          GONOSUMDB: github.com/celestiaorg/*

      - name: build
        run: make build
        env:
          GOPRIVATE: github.com/celestiaorg/*
          GONOSUMDB: github.com/celestiaorg/*
