name: ci-release

# Run this workflow on push events (i.e. PR merge) to main, feature/fibre or release branches,
# push events for new semantic version tags, and all PRs.
on:
  push:
    branches:
      - main
      - feature/fibre
      - "v*"
    tags:
      - "v*"
  release:
    types: [published]
  pull_request:
  merge_group:

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    secrets:
      GH_PRIVATE_MODULES_TOKEN: ${{ secrets.GH_PRIVATE_MODULES_TOKEN }}

  markdown-linter:
    uses: ./.github/workflows/markdown-linter.yml

  build:
    uses: ./.github/workflows/build.yml
    secrets:
      GH_PRIVATE_MODULES_TOKEN: ${{ secrets.GH_PRIVATE_MODULES_TOKEN }}

  test:
    uses: ./.github/workflows/test.yml
    secrets:
      GH_PRIVATE_MODULES_TOKEN: ${{ secrets.GH_PRIVATE_MODULES_TOKEN }}

  goreleaser:
    if: github.event_name == 'release'
    uses: ./.github/workflows/goreleaser.yml
    permissions: write-all
    secrets:
      GORELEASER_ACCESS_TOKEN: ${{ secrets.GORELEASER_ACCESS_TOKEN }}
      GH_PRIVATE_MODULES_TOKEN: ${{ secrets.GH_PRIVATE_MODULES_TOKEN }}
